woowacourse-teams/2023-stamp-crush

frontend/package.json
frontend/src/App.tsx
frontend/src/Router.tsx
frontend/src/components/Header.tsx
frontend/src/pages/Admin/CustomerList/index.tsx
frontend/src/pages/Admin/MakeCouponPolicy/index.tsx
frontend/src/pages/Admin/ManageCafe/index.tsx
frontend/src/pages/Admin/RegisterCafe/index.tsx
frontend/src/pages/CouponList/index.tsx
frontend/src/pages/EnterPhoneNumber/index.tsx
frontend/src/pages/History/index.tsx
frontend/src/pages/Login/index.tsx
frontend/src/pages/MyPage/index.tsx
frontend/src/pages/NotFound/index.tsx
frontend/src/pages/SignUp/index.tsx
frontend/webpack.common.js

close #23 
페어프로그래밍한 Router 입니다.

[FE] 페이지 라우팅 설정

---

frontend/.eslintrc.json

close #25 에 기반해 eslint 수정
검토후 approve 바랍니당

[FE] eslint 잘못된 규칙 정정

---

frontend/src/App.tsx
frontend/src/style/theme.ts

[FE] 전역으로 사용할 색상 정의

---

frontend/tsconfig.json

[FE] vscode 자동 import 경로가 잘못되는 문제

---

frontend/src/App.tsx
frontend/src/Router.tsx
frontend/src/components/Template/Template.style.tsx
frontend/src/components/Template/index.tsx

[FE] Template component 구현

---

frontend/tsconfig.json

close #61
- 경로 가져오기가 안 되는 문제 해결
- `tsconfig.json`에서 `baseUrl` 삭제
closes

[FE] fix: 경로 가져오기가 안 되는 문제 해결

---

frontend/tsconfig.json

죄송합니다! 이번엔 진짜 `baseUrl` 제거했습니다!🙇‍♂️
closes #64

[FE] fix: import 경로 불러오기 문제 해결

---

backend/src/main/java/com/stampcrush/backend/repository/cafe/CafeCouponDesignRepository.java
backend/src/main/java/com/stampcrush/backend/repository/cafe/CafePolicyRepository.java
backend/src/main/java/com/stampcrush/backend/repository/cafe/CafeRepository.java
backend/src/main/java/com/stampcrush/backend/repository/cafe/CafeStampCoordinateRepository.java
backend/src/main/java/com/stampcrush/backend/repository/coupon/CouponDesignRepository.java
backend/src/main/java/com/stampcrush/backend/repository/coupon/CouponPolicyRepository.java
backend/src/main/java/com/stampcrush/backend/repository/coupon/CouponRepository.java
backend/src/main/java/com/stampcrush/backend/repository/coupon/CouponStampCoordinateRepository.java
backend/src/main/java/com/stampcrush/backend/repository/coupon/StampRepository.java
backend/src/main/java/com/stampcrush/backend/repository/reward/RewardRepository.java
backend/src/main/java/com/stampcrush/backend/repository/user/CustomerRepository.java
backend/src/main/java/com/stampcrush/backend/repository/user/OwnerRepository.java

- repository생성했습니다..
- customer 상속 구조 관련 temporary, register customer repository 는 공부 후 구현 예정입니다
closes

[BE] feat: repository 작성

---

backend/build.gradle

[BE] chore: build.gradle에 RestAssured, Validation 패키지 의존성 추가

---

backend/build.gradle

- rest assured 버전 5.3.1로 수정했습니다.
closes #83

fix: rest-assured 버전 수정

---

frontend/src/components/Stepper/Stepper.style.tsx
frontend/src/components/Stepper/index.tsx

- Stepper 를 구현하였습니다. 피그마 시안대로 구현하려고 노력하였습니돠~
close #20 
```typescript
interface StepperProps {
minValue: number;
maxValue: number;
step: number;
value: number;
setValue: React.Dispatch<React.SetStateAction<number>>;
height: number;
}
```
`minValue`: Stepper가 가질 수 있는 최소값입니다.
`maxValue`: Stepper가 가질 수 있는 최대값입니다.
`step` : 증감버튼을 누를 때 마다 증가/감소하는 수치입니다.
`value` : 현재 Stepper의 값입니다. 리액트의 상태값입니다.
`setValue` : Stepper 값을 바꾸기 위한 useState Setter입니다.
`height`: Stepper의 높이를 설정합니다. Stepper는 디자인 상 크기조절할 때 비율을 맞추어야 되어 height만 받아 커스텀할 수 있게 구현하였습니다.

[FE] feat: Stepper 구현

---

backend/src/main/java/com/stampcrush/backend/exception/BadRequestException.java
backend/src/main/java/com/stampcrush/backend/exception/ForbiddenException.java
backend/src/main/java/com/stampcrush/backend/exception/NotFoundException.java
backend/src/main/java/com/stampcrush/backend/exception/StampCrushException.java
backend/src/main/java/com/stampcrush/backend/exception/UnAuthorizationException.java

- 커스텀 예외 작성
- 아래와 같이 상속받아서 사용하시면 됩니다! 
```mermaid
graph TD
RuntimeException --> StampCrushException
StampCrushException --> |400| BadRequestException
StampCrushException --> |401| UnAuthorizationException
StampCrushException --> |403| ForbiddenException
StampCrushException --> |404| NotFoundException
NotFoundException --> MemberNotFoundException
NotFoundException --> CouponNotFoundException
```
- 4인 페어로 진행
closes #97

[BE] feat: 커스텀 예외 작성

---

frontend/src/components/Input/Input.style.tsx
frontend/src/components/Input/index.tsx
frontend/src/components/SideBar/PageSideBar.tsx
frontend/src/components/SideBar/SideBar.style.tsx
frontend/src/components/SideBar/index.tsx
frontend/src/components/Template/Template.style.tsx
frontend/src/components/Template/index.tsx
frontend/src/pages/Admin/RegisterCafe/index.tsx
frontend/src/pages/Admin/RegisterCafe/style.tsx

- `Input`에 `{...props}` 추가 및 스타일 조정
- `SideBar` 스타일 조정도 함께 진행하였습니다. 혹시 충돌이 생길 수 있으니 주의해주세욥😇
closes #10

[FE] feat: 카페 등록 페이지를 구현한다.

---

frontend/src/components/SideBar/PageSideBar.tsx
frontend/src/components/SideBar/SideBar.style.tsx
frontend/src/components/Template/Template.style.tsx

[FE] refactor: Template 컴포넌트에 사이드바 추가

---

backend/.gitignore

- .http 를 실행하면 생성되는 로그 파일을 git 이 트래킹하지 않게 gitignore 추가했습니다
closes

[BE] feat: .gitignore 에 http-requests-log.http 추가

---

frontend/src/components/Modal/Modal.style.tsx
frontend/src/components/Modal/index.tsx
frontend/src/hooks/useModal.ts

- 공통 컴포넌트 개념의 모달 컴포넌트를 구현하였습니다.
구현 화면
+++ 🚨 기존의 방식을 사용하다보니 props drilling 이슈가 발생하여서 `useModal` 훅을 생성하여 모달을 관리할 예정입니다. 빠르게 수정하도록 하겠습니다.
closes #17

[FE] feat: 사장님 페이지의 모달 컴포넌트를 구현한다.

---

frontend/src/components/Template/Template.style.tsx
frontend/src/components/Template/index.tsx
frontend/src/components/Text/index.tsx
frontend/src/components/Text/style.ts
frontend/src/mocks/browser.ts
frontend/src/pages/Admin/CustomerList/index.tsx
frontend/src/pages/Admin/CustomerList/style.tsx

- 일단 지금 mockData도 없어서, 마크업 위주로 코드 리뷰 해주시면 감사하겠습니다!
close #19

[FE] feat: 내 고객리스트 컴포넌트 구현

---

frontend/package.json
frontend/src/components/SearchBar/index.tsx
frontend/src/components/SearchBar/style.ts
frontend/src/stories/SearchBar.stories.tsx

close #114 
스토리북 코드도 추가하였습니다!
외부에서 value와 setter를 props로 주입받아 동작하게끔 구현하였습니다. 
closes

[FE] feat: SearchBar 컴포넌트 구현

---

frontend/src/mocks/handlers.ts
frontend/src/mocks/mockData.ts

2차 데모데이 API 명세를 기반으로 하여 api를 모킹하였습니다. (#136)
closes #136

[FE] feat: 2차 데모데이 api 명세를 기반으로 api 모킹

---

frontend/package.json
frontend/src/App.tsx

[FE] feat: react-query 보일러 플레이팅

---

backend/src/main/java/com/stampcrush/backend/initializer/CouponSettingDataInitializer.java
backend/src/main/java/com/stampcrush/backend/initializer/SampleDataInitializer.java

[BE] feat: test CI (Initializer Profile dev로 변경)

---

backend/src/main/java/com/stampcrush/backend/initializer/SampleDataInitializer.java

[BE] style: 더미데이터 상수 변경

---

backend/src/main/java/com/stampcrush/backend/initializer/SampleDataInitializer.java
backend/src/main/resources/application-dev.yml

[BE] feat: application-dev 설정 변경

---

backend/src/main/java/com/stampcrush/backend/api/cafe/CafeApiController.java
backend/src/main/java/com/stampcrush/backend/initializer/CouponSettingDataInitializer.java
backend/src/main/java/com/stampcrush/backend/initializer/DataInitializer.java
backend/src/main/java/com/stampcrush/backend/initializer/SampleDataInitializer.java

[BE] feat: 더미데이터를 추가한다

---

backend/src/main/java/com/stampcrush/backend/api/sample/request/SampleCouponFindRequest.java

[BE] fix: max-stamp-count 쿼리 파라미터 바인딩 설정

---

backend/src/main/java/com/stampcrush/backend/api/sample/request/SampleCouponFindRequest.java

[BE] fix: SampleCouponFindRequest 생성자 에러 수정

---

backend/src/main/java/com/stampcrush/backend/application/cafe/CafeCouponSettingService.java
backend/src/main/java/com/stampcrush/backend/application/cafe/CafeNotFoundException.java
backend/src/main/java/com/stampcrush/backend/entity/cafe/CafeCouponDesign.java
backend/src/main/java/com/stampcrush/backend/entity/cafe/CafePolicy.java
backend/src/main/java/com/stampcrush/backend/initializer/CouponSettingDataInitializer.java
backend/src/test/java/com/stampcrush/backend/acceptance/CafeCouponSettingIntegrationTest.java

- 마찬가지로 테스트 격리는 템플릿 만들어지는대로 갈아타겠습니다.
- 소프트 딜리트 구현하는 법을 공부해서 잘 적용해봤습니다. 이것도 어노테이션 빼도 될 것 같은데, 좀더 테스트해보고 만들겠습니다. 
closes #120

[BE] test: Cafe Coupon Setting 수정 API에 대한 테스트 코드를 작성한다

---

backend/src/main/java/com/stampcrush/backend/application/coupon/CouponService.java
backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
backend/src/main/java/com/stampcrush/backend/entity/coupon/CouponStatus.java
backend/src/test/java/com/stampcrush/backend/repository/coupon/CouponRepositoryTest.java

- 이번건 진짜 이름만 바꿨어요 
- 빠른 머지 요청 💋
closes #155

[BE] style: Coupon Status USING -> ACCUMULATING으로 변경

---

frontend/src/components/Dialpad/index.tsx
frontend/src/hooks/useDialPad.ts
frontend/src/pages/EnterPhoneNumber/index.tsx
frontend/src/pages/EnterPhoneNumber/style.tsx

[FE] refactor: enter로직 구현, 뒤로가기 추가

---

frontend/src/Router.tsx
frontend/src/components/ModalContents/StampAndReward.style.tsx
frontend/src/mocks/handlers.ts
frontend/src/pages/Admin/RewardPage/index.tsx

- 리워드 사용 기능에 msw를 기반으로 api를 입혔습니다.
closes #141

[FE] feat: 리워드 사용 기능을 구현한다.

---

backend/src/main/java/com/stampcrush/backend/api/cafe/CafeApiController.java
backend/src/main/java/com/stampcrush/backend/api/cafe/CafeCouponSettingApiController.java
backend/src/main/java/com/stampcrush/backend/api/coupon/CouponApiController.java
backend/src/main/java/com/stampcrush/backend/api/customer/CustomerApiController.java
backend/src/main/java/com/stampcrush/backend/api/reward/RewardApiController.java
backend/src/main/java/com/stampcrush/backend/api/sample/SampleCouponApiController.java
backend/src/test/java/com/stampcrush/backend/acceptance/CustomerIntegrationTest.java

-  f backend api uri api prefix 추가
closes #152

[BE] feat: backend api uri api prefix 추가

---

backend/src/test/java/com/stampcrush/backend/acceptance/CafeCouponSettingIntegrationTest.java
backend/src/test/java/com/stampcrush/backend/acceptance/SampleCouponIntegrationTest.java

[BE] fix: 테스트 코드에 /api prefix 추가

---

backend/src/main/java/com/stampcrush/backend/api/cafe/CafeApiController.java
backend/src/main/java/com/stampcrush/backend/api/cafe/request/CafeCreateRequest.java

- refactor: Request DTO record로 분리
closes

[BE] test: CI/CD 파이프라인에 테스트 돌려보는 코드 추가

---

backend/src/main/java/com/stampcrush/backend/api/coupon/CouponApiController.java
backend/src/main/java/com/stampcrush/backend/initializer/DataInitializer.java
backend/src/main/java/com/stampcrush/backend/initializer/SampleDataInitializer.java

[BE] fix: 더미 데이터 수정

---

backend/src/main/java/com/stampcrush/backend/api/coupon/response/CafeCustomerFindResponse.java
backend/src/main/java/com/stampcrush/backend/api/coupon/response/CustomerAccumulatingCouponFindResponse.java
backend/src/main/java/com/stampcrush/backend/application/coupon/CouponService.java
backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CafeCustomerFindResultDto.java
backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CustomerAccumulatingCouponFindResultDto.java
backend/src/test/java/com/stampcrush/backend/application/coupon/CouponServiceTest.java

[BE]: 고객 목록 조회, 고객 쿠폰 조회 시 maxStampCount 더미 데이터 추가

---

backend/src/main/java/com/stampcrush/backend/initializer/DataInitializer.java

[BE] fix: 더미데이터 추가 변경

---

frontend/src/mocks/handlers.ts
frontend/src/pages/Admin/EarnStamp/index.tsx

- 스탬프 적립 api 명세 변경에 따라 리팩터링하였습니다 . `ownerId` 추가
closes #177

[FE] refactor: 스탬프 적립 api 명세 변경에 따라 리팩터링한다.

---

backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
backend/src/test/java/com/stampcrush/backend/application/coupon/CouponServiceTest.java

[BE ]feat: 고객 방문횟수 계산 로직 수정

---

frontend/src/mocks/handlers.ts
frontend/src/pages/Admin/RegisterCafe/index.tsx

- 카페 등록 페이지의 api 요청 로직을 구현했습니다.
closes #166

[FE] feat: 카페 등록 페이지의 api 요청 로직 구현 

---

backend/src/main/java/com/stampcrush/backend/api/coupon/response/CafeCustomerFindResponse.java
backend/src/main/java/com/stampcrush/backend/api/coupon/response/CustomerAccumulatingCouponFindResponse.java

[BE] feat: dto boolean 래퍼클래스로 수정

---

backend/src/main/java/com/stampcrush/backend/initializer/SampleDataInitializer.java

- 2차 데모 시연을 위해 샘플 쿠폰에 이미지 추가했습니다
closes

[BE] feat: 2차 데모 시연을 위한 샘플 쿠폰에 이미지 추가

---

backend/src/main/java/com/stampcrush/backend/api/coupon/response/CafeCustomerFindResponse.java
backend/src/main/java/com/stampcrush/backend/api/coupon/response/CustomerAccumulatingCouponFindResponse.java

[BE] feat: api date포맷 변경

---

backend/src/main/java/com/stampcrush/backend/config/WebMvcConfig.java

[BE] feat: CORS 설정한다. 

---

backend/src/main/java/com/stampcrush/backend/config/WebMvcConfig.java

[BE] feat: 모든 IP 대역에서 응답받을 수 있도록 CORS 설정 변경

---

backend/src/main/java/com/stampcrush/backend/config/WebMvcConfig.java

[BE] fix: cors 전체 허용으로 바꿨는데 이슈 발생으로 원복

---

backend/src/main/java/com/stampcrush/backend/api/coupon/CouponApiController.java
backend/src/main/java/com/stampcrush/backend/application/cafe/CafeCouponSettingService.java
backend/src/main/java/com/stampcrush/backend/application/cafe/CafeService.java
backend/src/main/java/com/stampcrush/backend/application/coupon/CouponService.java
backend/src/main/java/com/stampcrush/backend/application/coupon/CustomerCouponStatistics.java
backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CafeCustomerFindResultDto.java
backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CustomerAccumulatingCouponFindResultDto.java
backend/src/main/java/com/stampcrush/backend/application/customer/CustomerService.java
backend/src/main/java/com/stampcrush/backend/exception/CafeNotFoundException.java
backend/src/main/java/com/stampcrush/backend/exception/CustomerBadRequestException.java
backend/src/main/java/com/stampcrush/backend/exception/CustomerNotFoundException.java
backend/src/main/java/com/stampcrush/backend/exception/OwnerNotFoundException.java
backend/src/test/java/com/stampcrush/backend/application/coupon/CouponServiceTest.java
backend/src/test/java/com/stampcrush/backend/fixture/CouponDesignFixture.java
backend/src/test/java/com/stampcrush/backend/fixture/CouponPolicyFixture.java
backend/src/test/java/com/stampcrush/backend/fixture/CustomerFixture.java
backend/src/test/java/com/stampcrush/backend/fixture/OwnerFixture.java

- Service 계층: 메서드 분리 통해서 복잡한 로직은 최대한 가독성 있게 수정함.
- test 코드: 가능한 만큼 Fixture 분리함.
- 매 commit 전에 전체 테스트코드 통과하는지 확인했습니다. 
- 본인 코드인 부분에 대해서 마음에 안드는 수정이 있다면 댓글로 말해주세요!
- 3차 데모데이 코드 시작 전에 반드시 merge해야 합니다.
closes #171

[BE] refactor: 2차 데모데이까지의 코드를 리팩터링한다. 

---

backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java

- #192 머지하다가 실수로 한 개 메서드를 삭제해서 추가 후 새 PR 만들었습니다.
- 현재 테스트 모두 통과하는 중
- 바로 머지해도 될 것 같습니다
closes

[BE] fix: merge conflict 해결

---

.github/workflows/backend_ci.yml

- Jenkins만을 사용했더니, 테스트가 통과하지 않는 코드도 머지된 이후에 문제가 발생된다는 문제점이 발생했습니다.
- 깃허브 액션으로 push, pull request에 대해서도 테스트 코드 및 빌드가 진행되는지 검사를 추가했습니다. 
closes

[BE] feat: Github Action을 통해 CI 설정

---

backend/src/main/java/com/stampcrush/backend/application/coupon/CouponService.java
backend/src/main/java/com/stampcrush/backend/application/coupon/CustomerCouponStatistics.java
backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CustomerAccumulatingCouponFindResultDto.java
backend/src/main/java/com/stampcrush/backend/application/customer/CustomerService.java
backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupons.java
backend/src/main/java/com/stampcrush/backend/entity/user/TemporaryCustomer.java
backend/src/main/java/com/stampcrush/backend/initializer/DataInitializer.java
backend/src/test/java/com/stampcrush/backend/acceptance/CustomerIntegrationTest.java
backend/src/test/java/com/stampcrush/backend/application/coupon/CouponServiceTest.java
backend/src/test/java/com/stampcrush/backend/application/customer/CustomerServiceTest.java
backend/src/test/java/com/stampcrush/backend/application/reward/RewardServiceTest.java
backend/src/test/java/com/stampcrush/backend/entity/coupon/CouponTest.java
backend/src/test/java/com/stampcrush/backend/entity/reward/RewardTest.java
backend/src/test/java/com/stampcrush/backend/fixture/CustomerFixture.java
backend/src/test/java/com/stampcrush/backend/repository/coupon/CouponRepositoryTest.java

- 2차 데모데이 리팩터링 코드 리뷰 반영했습니다
- 깃짱 하디랑 같이 함
closes #198

[BE] refactor : 2차 데모데이 기능 구현한 코드를 리팩터링한다

---

backend/src/main/java/com/stampcrush/backend/api/ExceptionResponse.java
backend/src/main/java/com/stampcrush/backend/api/GlobalExceptionHandler.java
backend/src/test/java/com/stampcrush/backend/acceptance/CustomerIntegrationTest.java

- 전역 예외 처리
- @yenawee 에게.. 하디랑 테스트 통해서 이렇게 가도 `MethodArgumentNotValidException` 잘 잡힌다는거 확인함
3인 페어로 진행
closes #101

[BE] feat: 전역 예외 처리

---

backend/src/main/java/com/stampcrush/backend/api/cafe/CafeApiController.java
backend/src/main/java/com/stampcrush/backend/api/cafe/CafeCouponSettingApiController.java
backend/src/main/java/com/stampcrush/backend/api/coupon/CouponApiController.java
backend/src/main/java/com/stampcrush/backend/api/reward/RewardApiController.java

- #215 에서 Request DTO를 잘 만들고도, `@Valid` 어노테이션을 추가하지 않는 큰 실수를 했습니다...
- 추가했습니다 >< 
- 빠른 머지일수록 좋을 것 같습니다
closes

[BE] fix: Api Controller의 Request에 Valid 어노테이션 추가

---

backend/build.gradle
backend/src/main/java/com/stampcrush/backend/config/SwaggerConfig.java

- Swagger로 했습니다.
- 이후에 RestDocs 집념의 제나가 수정해서 성공하게 되면 이 부분은 삭제해도 됩니다. 
closes #225

[BE] feat: swagger 사용해서 API 자동화 추가

---

frontend/src/pages/Admin/CustomCouponDesign/index.tsx
frontend/src/pages/Admin/ModifyCouponPolicy/index.tsx
frontend/src/pages/Admin/SelectCoupon/index.tsx
frontend/src/pages/EnterPhoneNumber/index.tsx
frontend/src/utils/index.ts

- 기존 코드에서 많은 부분이 반영이 되있더라구요 ?! 고생하셨습니다 ㅎㅎ :D
closes #164

[FE] feat: 2차 데모데이 api를 백엔드와 연동한다.

---

frontend/src/api/get.ts
frontend/src/api/patch.ts
frontend/src/api/post.ts
frontend/src/mocks/handlers.ts

- 사장모드 요청때 /admin -prefix를 붙이자고 결론이 나 수정했습니다.
closes #253

[FE] feat: msw 핸들러 및 api 메소드 구현

---

frontend/src/components/Alert/index.tsx
frontend/src/components/Alert/style.tsx
frontend/src/mocks/mockData.ts
frontend/src/pages/CouponList/index.tsx
frontend/src/stories/Alert.stories.tsx

- 즐겨찾기 무한 요청 방지, 삭제 기능 확인 등 고객모드에서 쓰일 Alert를 구현하였습니다. 
closes #208

[FE] feat: 고객모드 Alert Component 구현

---

frontend/src/api/post.ts
frontend/src/components/Alert/style.tsx
frontend/src/mocks/handlers.ts
frontend/src/mocks/mockData.ts
frontend/src/pages/CouponList/Coupon/style.tsx
frontend/src/pages/CouponList/index.tsx
frontend/src/pages/CouponList/style.tsx

- 즐겨찾기 등록 및 해제 기능입니다.
- msw에서 현재 즐겨찾기 등록 및 해제 api handler를 무조건 200을 주게 구현을 해놓은 상태여서 테스트를 하는데 어려움이 있습니다.
- 백엔드실제서버를 연동했을때는 react-query와 내부에서 잘 업데이트가 될거라고 예상이 되는데 리뷰어님들의 의견은 어떠신가요? 
closes #256

[FE] feat: 즐겨찾기 변경 기능 구현

---

frontend/src/api/get.ts
frontend/src/api/patch.ts
frontend/src/api/post.ts
frontend/src/mocks/handlers.ts
frontend/src/pages/Admin/CustomCouponDesign/index.tsx
frontend/src/pages/Admin/EarnStamp/index.tsx
frontend/src/pages/Admin/RegisterCafe/index.tsx

- api 뿐만아니라 이전에 명세와 다른 부분도 전부 변경했습니다~~
closes #268

[FE] fix: api 명세 변경에 따른 api 관련 코드 리팩터링을 한다.

---

frontend/src/pages/CouponList/CouponDetail/style.tsx
frontend/src/style/keyframes.ts

- 가로 및 세로 스크롤이 가능하지 않도록 모달이 열리는 방식 수정하였습니다.
closes #274

[FE] fix: 가로 및 세로 스크롤이 가능하지 않도록 모달이 열리는 방식 수정

---

backend/src/main/resources/application-dev.yml

- datasource 설정했음
- 비밀인 내용은 환경변수 별도로 설정해줘야 함
closes

[BE] setting: dev 설정 파일 업데이트

---

backend/src/main/java/com/stampcrush/backend/initializer/DataInitializer.java
backend/src/main/java/com/stampcrush/backend/initializer/SampleDataInitializer.java
backend/src/main/resources/application-dev.yml

[BE] setting: application-dev.yml ddl-auto validate로 수정

---

backend/src/main/java/com/stampcrush/backend/api/manager/cafe/ManagerCafeCommandApiController.java
backend/src/main/java/com/stampcrush/backend/api/visitor/coupon/VisitorCustomerCouponFindApiController.java
backend/src/main/java/com/stampcrush/backend/api/visitor/favorites/VisitorFavoritesCommandApiController.java
backend/src/main/java/com/stampcrush/backend/application/visitor/favorites/VisitorFavoritesCommandService.java
backend/src/main/java/com/stampcrush/backend/config/resolver/CustomerAuth.java
backend/src/test/java/com/stampcrush/backend/acceptance/CustomerCouponFindAcceptanceTest.java
backend/src/test/java/com/stampcrush/backend/application/favorites/VisitorFavoritesCommandServiceTest.java

[BE] fix: API에 맞도록 수정한다

---

backend/src/test/java/com/stampcrush/backend/acceptance/CustomerCouponFindAcceptanceTest.java
backend/src/test/java/com/stampcrush/backend/acceptance/step/CouponFindStep.java

- API를 3차 데모데이 변경과 맞게 하면서 급하게 머지하기 위해서 테스트를 Disable 해놨는데, 버그 수정하고 다시 Disable 풀어놨어요
#288 과 관련있습니다!

[BE] fix: Customer Coupon Find API 인수테스트 버그 수정 (테스트코드만 수정했음)

---

backend/src/main/java/com/stampcrush/backend/api/manager/cafe/ManagerCafeCommandApiController.java
backend/src/main/java/com/stampcrush/backend/api/manager/cafe/ManagerCafeFindApiController.java
backend/src/main/java/com/stampcrush/backend/api/manager/coupon/ManagerCouponCommandApiController.java
backend/src/main/java/com/stampcrush/backend/api/manager/coupon/ManagerCouponFindApiController.java
backend/src/main/java/com/stampcrush/backend/api/visitor/coupon/VisitorCustomerCouponFindApiController.java
backend/src/main/java/com/stampcrush/backend/config/resolver/OwnerAuth.java
backend/src/test/java/com/stampcrush/backend/api/cafe/ManagerCafeFindApiControllerTest.java

- 3차 데모데이 때 바꾸기로 한 내용들 반영 안된거 싹 바꿨습니다
closes #291

[BE] fix: 수정된 API에 맞게 Controller 수정

---

backend/src/main/resources/application-dev.yml

[BE] refactor: ddl-auto 수정

---

backend/src/main/java/com/stampcrush/backend/api/visitor/cafe/response/CafeInfoFindResponse.java
backend/src/main/java/com/stampcrush/backend/api/visitor/coupon/response/CustomerCouponFindResponse.java

[BE] fix: json-format-change

---

backend/src/main/java/com/stampcrush/backend/api/visitor/cafe/response/CafeInfoFindResponse.java
backend/src/main/java/com/stampcrush/backend/api/visitor/coupon/response/CustomerCouponFindResponse.java

[BE} fix:json format

---

backend/src/main/java/com/stampcrush/backend/api/visitor/coupon/response/CustomerCouponFindResponse.java

[BE] refactor: getter 수동으로 작성

---

frontend/src/api/index.ts

[FE] fix: api base url 수정

---

backend/src/main/java/com/stampcrush/backend/api/manager/cafe/response/CafeFindResponse.java
backend/src/main/java/com/stampcrush/backend/application/manager/cafe/dto/CafeFindResultDto.java

[BE] feat: CafeFindResponse에 introduction 추가

---

frontend/src/api/patch.ts

[FE] fix: 잘못된 api 엔드포인트 수정

---

backend/src/main/java/com/stampcrush/backend/application/manager/cafe/SampleCouponImage.java
backend/src/main/java/com/stampcrush/backend/entity/cafe/CafeCouponDesign.java

[BE] feat: 시연용 쿠폰 사진 추가

---

backend/src/main/java/com/stampcrush/backend/api/manager/sample/response/SampleCouponFindResponse.java

[BE] bug: coupon setting api 명세에 맞게 수정 

---

backend/src/main/java/com/stampcrush/backend/application/manager/cafe/ManagerCafeCommandService.java
backend/src/main/java/com/stampcrush/backend/application/manager/cafe/SampleCouponImage.java

- 라잇이 보내준 스탬프 좌표로 변경함.
- 해당 내용은 카페 자체를 처음 생성할 때 들어가는 내용으로, 쿠폰만을 새로 생성할 때는 해당사항 없음
closes

[BE] feat: Stamp Coordinates 커스텀으로 변경

---

backend/src/main/java/com/stampcrush/backend/entity/cafe/CafeCouponDesign.java
backend/src/main/java/com/stampcrush/backend/entity/cafe/CafePolicy.java

- 이걸로 고쳐질 지 모르겠지만.. 부디 고쳐지면 좋겠습니다
closes

[BE] fix: sql 테이블명 대문자를 소문자로 변경

---

frontend/src/components/Alert/index.tsx
frontend/src/components/Header/index.tsx
frontend/src/components/Modal/index.tsx
frontend/src/mocks/mockData.ts
frontend/src/pages/Admin/ManageCafe/index.tsx
frontend/src/pages/CouponList/CouponDetail/style.tsx
frontend/src/pages/CouponList/FlippedCoupon/style.tsx
frontend/src/pages/CouponList/index.tsx

[FE] feat: 웹접근성 및 스타일 수정

---

frontend/src/pages/CouponList/Coupon/index.tsx
frontend/src/pages/CouponList/Coupon/style.tsx
frontend/src/pages/CouponList/index.tsx

[FE] fix: 배포 오류 해결

---

frontend/src/api/patch.ts

[FE] fix: api 명세 따른 변경

---

frontend/src/components/SideBar/PageSideBar.tsx
frontend/src/components/SideBar/style.tsx
frontend/src/constants/index.ts
frontend/src/mocks/mockData.ts
frontend/src/pages/Admin/CustomerList/index.tsx
frontend/src/pages/CouponList/FlippedCoupon/style.tsx
frontend/src/pages/CouponList/index.tsx
frontend/src/style/keyframes.ts

[FE] bug: react-query refetch 관련 문제 수정

---

backend/src/main/java/com/stampcrush/backend/api/manager/sample/response/SampleCouponFindResponse.java
backend/src/main/java/com/stampcrush/backend/application/manager/sample/ManagerSampleCouponFindService.java
backend/src/main/java/com/stampcrush/backend/application/manager/sample/dto/SampleCouponsFindResultDto.java

- 이전 코드에서 Service DTO에서 Entity 객체를 그대로 반환하던 문제가 있어서 수정했습니다.
- 결과에는 변화가 없습니다! 
closes #315

[BE] fix: SampleCouponsFindResultDto에서 entity를 반환하던 문제 해결

---

frontend/src/components/Text/index.tsx
frontend/src/pages/Admin/EarnStamp/index.tsx
frontend/src/pages/CouponList/CouponDetail/index.tsx
frontend/src/pages/CouponList/index.tsx

[FE] fix: 하드코딩 부분 및 웹접근성 수정

---

backend/src/test/java/com/stampcrush/backend/api/manager/cafe/ManagerCafeCouponSettingCommandApiControllerTest.java
backend/src/test/java/com/stampcrush/backend/api/manager/sample/ManagerSampleCouponFindApiControllerTest.java
backend/src/test/java/com/stampcrush/backend/api/visitor/coupon/VisitorCouponFindApiControllerTest.java
backend/src/test/java/com/stampcrush/backend/helper/AuthHelper.java

- 레오가 줬던 피드백을 반영하지 못했는데, 곧바로 머지를 해버려서 별도로 브랜치 팠어요! 
- 리뷰줬던 내용 반영했습니당! 
closes

[BE] refactor: AuthHelper로 인증 관련 코드 분리

---

backend/src/test/java/com/stampcrush/backend/api/visitor/coupon/VisitorCouponFindApiControllerTest.java
backend/src/test/java/com/stampcrush/backend/fixture/CafeFixture.java
backend/src/test/java/com/stampcrush/backend/fixture/CouponDesignFixture.java
backend/src/test/java/com/stampcrush/backend/fixture/CouponFixture.java
backend/src/test/java/com/stampcrush/backend/fixture/CouponPolicyFixture.java
backend/src/test/java/com/stampcrush/backend/fixture/CustomerFixture.java
backend/src/test/java/com/stampcrush/backend/fixture/OwnerFixture.java
backend/src/test/java/com/stampcrush/backend/fixture/SampleCouponFixture.java
backend/src/test/java/com/stampcrush/backend/helper/AuthHelper.java

[BE] refactor: Fixture 클래스 final 제어자, private 생성자 추가

---

backend/src/main/java/com/stampcrush/backend/config/WebMvcConfig.java
backend/src/main/resources/application-dev.yml
backend/src/main/resources/application.yml

- swagger URL 에 접근할때 인터셉터 걸려서 pathpattern 추가했습니다
- 윤생이랑 레고한테 부탁했어요
closes

[BE] feat: swagger ui 인터셉터 설정 및 url 설정 변경

---

backend/src/main/java/com/stampcrush/backend/config/WebMvcConfig.java
backend/src/main/resources/logback-spring.xml

- 간단한 설정이라서 한 번 보고 궁금한거 물어봐주세요! 
- [테코톡 발표자료](https://docs.google.com/presentation/d/1toZ10axF1o8I1KiZg0fyHSZ-LzarqusX/edit?usp=sharing&ouid=116931641468088042880&rtpof=true&sd=true) 보면 거의 이해가 될거에요!
- 아직 로그에 색깔이 없어요..ㅋㅋ 못봐주겠는데 어떻게 설정해야하는지 좀 찾기가 어려워서 가능한 분은 만들어서 PR 올려주시거나 여기에 커밋 쌓아줘도 좋아요
closes #381

[BE] feat: 로깅 기능 추가

---

backend/src/main/java/com/stampcrush/backend/config/LogFormat.java

[BE] feature: log-format 로깅 문자열 추가

---

backend/src/test/java/com/stampcrush/backend/acceptance/FavoritesAcceptanceTest.java
backend/src/test/java/com/stampcrush/backend/api/favorites/VisitorFavoritesCommandApiControllerTest.java

- 즐겨찾기 등록, 해제 테스트 작성
closes #344

[BE] refactor: 즐겨찾기 등록 및 해제 기능 테스트 작성

---

frontend/src/pages/CouponList/index.tsx

[FE] fix: useEffect import 추가

---

backend/src/main/java/com/stampcrush/backend/application/manager/coupon/ManagerCouponCommandService.java
backend/src/main/java/com/stampcrush/backend/application/manager/coupon/dto/CustomerAccumulatingCouponFindResultDto.java
backend/src/main/java/com/stampcrush/backend/entity/cafe/Cafe.java
backend/src/test/java/com/stampcrush/backend/application/coupon/ManageCouponCommandServiceTest.java
backend/src/test/java/com/stampcrush/backend/application/coupon/ManagerCouponFindServiceTest.java
backend/src/test/java/com/stampcrush/backend/repository/cafe/CafePolicyRepositoryTest.java

#336 PR의 리뷰사항들 반영했습니다.
closes #409

[BE] refactor: coupon service테스트 관련 리뷰 적용했습니다.

---

backend/src/main/java/com/stampcrush/backend/entity/visithistory/VisitHistory.java

- VisitHistory엔티티 생성했습니다~
closes #383

[BE] feat: visit_history엔티티 생성

---

backend/src/main/java/com/stampcrush/backend/config/WebMvcConfig.java
backend/src/main/resources/application-dev.yml
backend/src/main/resources/application.yml

- 개발환경에서 swagger 페이지가 접근되지 않아서 설정파일 수정해봤습니다....
closes

[BE] feat: 개발환경에서 swagger 페이지가 접근되지 않아서 설정파일 수정

---

backend/src/main/resources/logback-spring.xml

- 색깔이 안들어가서 너무 침침했는데 적용에 성공했습니다! 
closes #423

[BE] feat: 로그에 스프링부트와 동일한 색상 적용

---

backend/.gitignore

- 로깅 파일 출력되는 디렉토리들을 .gitignore 에 추가했습니다
closes

[BE] chore: .gitignore 에 log 디렉토리 추가

---

backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCouponCommandIntegrationTest.java
backend/src/test/java/com/stampcrush/backend/api/manager/coupon/ManagerCouponCommandApiControllerTest.java
backend/src/test/java/com/stampcrush/backend/api/manager/coupon/ManagerCouponFindApiControllerTest.java
backend/src/test/java/com/stampcrush/backend/api/manager/reward/ManagerRewardFindApiControllerTest.java
backend/src/test/java/com/stampcrush/backend/api/manager/reward/MangerRewardCommandApiControllerTest.java
backend/src/test/java/com/stampcrush/backend/api/visitor/favorites/VisitorFavoritesCommandApiControllerTest.java
backend/src/test/java/com/stampcrush/backend/application/manager/cafe/ManagerCafeCommandServiceTest.java
backend/src/test/java/com/stampcrush/backend/application/manager/coupon/ManageCouponCommandServiceTest.java
backend/src/test/java/com/stampcrush/backend/application/manager/coupon/ManagerCouponFindServiceTest.java
backend/src/test/java/com/stampcrush/backend/application/manager/reward/ManagerRewardCommandServiceTest.java
backend/src/test/java/com/stampcrush/backend/application/visitor/favorites/VisitorFavoritesCommandServiceTest.java

- 이전에 manager, visitor 구조로 변경하면서 테스트 코드는 함께 변경하지 않아서 이후에 생성된 테스트코드랑 혼동이 좀 있어서, 변경했습니다. 
- 변경 결과는 아래와 같이 매우 깔끔해졌습니다.
closes

[BE] chore: 테스트 코드 패키지 정리

---

frontend/src/components/SideBar/PageSideBar.tsx
frontend/src/pages/Admin/RegisterCafe/index.tsx

- 변경된 디자인에서는 사이드바를 렌더링하지 않는 편이 UI가 자연스러운 것으로 판단하여 카페 등록 페이지에 진입시 사이드바를 렌더링하지 않도록 하였습니다.
- 추후에 카페 등록 옵션을 사이드바에 추가하는 것도 괜찮아 보입니다.
closes #275

[FE] refactor: 카페 등록 페이지의 사이드바를 렌더링하지 않는다.

---

backend/src/main/java/com/stampcrush/backend/api/manager/auth/ManagerAuthController.java
backend/src/main/java/com/stampcrush/backend/api/manager/auth/ManagerAuthService.java
backend/src/main/java/com/stampcrush/backend/api/manager/auth/StateUtils.java
backend/src/main/java/com/stampcrush/backend/config/WebMvcConfig.java

- 비밀 정보는 코드에 불포함
- 코드 자체는 리팩터링 예정
closes

[BE] feat: OAuth 최초 요청에 대해서 Resource Server에 접근할 Redirect URI 응답

---

backend/src/main/java/com/stampcrush/backend/api/manager/auth/ManagerAuthController.java
backend/src/main/java/com/stampcrush/backend/config/WebMvcConfig.java

[BE] feat: /api/owners/oauth/naver에 대해서 인증 제외

---

backend/src/main/java/com/stampcrush/backend/api/manager/auth/ManagerAuthController.java
backend/src/main/java/com/stampcrush/backend/application/manager/auth/ManagerAuthService.java

[BE] feat: Login API Get 으로 변경

---

frontend/src/pages/Admin/AdminLogin/index.tsx

[FE] refactor: 카카오로 테스트

---

backend/src/main/java/com/stampcrush/backend/api/manager/auth/ManagerAuthController.java
backend/src/main/java/com/stampcrush/backend/application/manager/auth/ManagerAuthService.java

[BE] feat: 카카오 로그인 요청 API 생성

---

backend/src/main/java/com/stampcrush/backend/api/manager/coupon/response/CafeCustomerFindResponse.java
backend/src/main/java/com/stampcrush/backend/api/manager/coupon/response/CafeCustomersFindResponse.java
backend/src/main/java/com/stampcrush/backend/application/manager/coupon/CustomerCouponStatistics.java
backend/src/main/java/com/stampcrush/backend/application/manager/coupon/ManagerCouponFindService.java
backend/src/main/java/com/stampcrush/backend/application/manager/coupon/dto/CafeCustomerFindResultDto.java
backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupons.java
backend/src/main/java/com/stampcrush/backend/entity/user/Owner.java
backend/src/main/java/com/stampcrush/backend/entity/visithistory/VisitHistories.java
backend/src/main/java/com/stampcrush/backend/entity/visithistory/VisitHistory.java
backend/src/main/java/com/stampcrush/backend/exception/VisitHistoryNotFoundException.java
backend/src/main/java/com/stampcrush/backend/repository/visithistory/VisitHistoryRepository.java
backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCouponFindAcceptanceTest.java
backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerCafeCreateStep.java
backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerCustomerFindStep.java
backend/src/test/java/com/stampcrush/backend/application/manager/coupon/ManagerCouponFindServiceTest.java
backend/src/test/java/com/stampcrush/backend/fixture/OwnerFixture.java
backend/src/test/java/com/stampcrush/backend/repository/visithistory/VisitHistoryRepositoryTest.java

-  이전 PR 충돌해결하다 리베이스 잘못해서 다시 올려요
closes #414

[BE] refactor: 고객의 방문횟수 계산하는 로직을 수정한다

---

backend/src/test/java/com/stampcrush/backend/api/docs/DocsControllerTest.java
backend/src/test/java/com/stampcrush/backend/api/docs/manager/sample/ManagerSampleCouponFindApiDocsControllerTest.java
backend/src/test/java/com/stampcrush/backend/api/docs/visitor/coupon/VisitorCouponCommandApiDocsControllerTest.java
backend/src/test/java/com/stampcrush/backend/api/docs/visitor/reward/VisitorRewardsFindApiDocsControllerTest.java
backend/src/test/java/com/stampcrush/backend/api/docs/visitor/visithistory/VisitorVisitHistoryFindApiDocsControllerTest.java

- 4차 데모데이때 추가된 API 명세 테스트를 작성했습니다
closes

[BE] feat: 4차 데모데이 기능구현한 API 명세 테스트를 작성한다

---

backend/src/main/java/com/stampcrush/backend/config/WebMvcConfig.java

- 매번 API 추가마다 매번 수정해야 하는 문제가 생겨서, addPattern 부분을 수정했습니다.
- 추후에 추가될 /api/login 부분도 고려해서 미리 추가해놨습니다 
closes

[BE] refactor: auth 관련 pattern 수정

---

backend/src/main/java/com/stampcrush/backend/api/LogController.java

[BE] feat: cloud watch테스트용 로그 작성

---

backend/src/main/java/com/stampcrush/backend/api/LogController.java
backend/src/test/java/com/stampcrush/backend/api/docs/visitor/reward/VisitorRewardsFindApiDocsControllerTest.java

[BE] feat: cloud watch log test

---

.gitmodules

[BE] feat: sub-module생성

---

.gitmodules
backend/src/main/resources/application-dev.yml
backend/src/main/resources/application-prod.yml
backend/src/main/resources/application.yml

[BE] feat: sub module

---

.gitmodules
backend/src/main/resources/application-dev.yml
backend/src/main/resources/application-prod.yml
backend/src/main/resources/application.yml

[BE] feat: Sub module설정 변경

---

.gitmodules
backend/src/main/resources/application-dev.yml
backend/src/main/resources/application-prod.yml
backend/src/main/resources/application.yml

[BE] feat: Sub module수정

---

backend/src/main/java/com/stampcrush/backend/initializer/DataInitializer.java

[BE] refactor: 주석 제거 (Jenkins trigger 테스트용)

---

backend/src/main/java/com/stampcrush/backend/config/TestConfig.java

[FE] test: Jenkins 파이프라인 테스트용 커밋

---

frontend/src/Router.tsx

[FE] fix: 잘못된 import문 수정

---

frontend/src/pages/Admin/AdminAuth/index.tsx

[FE] fix: 주석 제거

---

backend/src/main/java/com/stampcrush/backend/api/manager/cafe/ManagerCafeCouponSettingFindApiController.java
backend/src/main/java/com/stampcrush/backend/api/manager/cafe/response/CafeCouponCoordinateFindResponse.java
backend/src/main/java/com/stampcrush/backend/api/manager/cafe/response/CafeCouponSettingFindResponse.java
backend/src/main/java/com/stampcrush/backend/application/manager/cafe/ManagerCafeCouponSettingFindService.java
backend/src/main/java/com/stampcrush/backend/application/manager/cafe/dto/CafeCouponCoordinateFindResultDto.java
backend/src/main/java/com/stampcrush/backend/application/manager/cafe/dto/CafeCouponSettingFindResultDto.java
backend/src/main/java/com/stampcrush/backend/exception/CafeCouponSettingNotFoundException.java
backend/src/test/java/com/stampcrush/backend/api/manager/cafe/ManagerCafeCouponSettingFindApiControllerTest.java
backend/src/test/java/com/stampcrush/backend/application/manager/cafe/ManagerCafeCouponSettingFindServiceTest.java

[BE] feat: 카페 사장이 카페 쿠폰 세팅을 조회한다.

---

frontend/src/api/get.ts
frontend/src/api/index.ts
frontend/src/pages/Admin/AdminAuth/index.tsx
frontend/src/pages/Auth/index.tsx

[FE] fix: oAuth 테스트 중 발견한 이슈 해결

---

frontend/src/Router.tsx
frontend/src/api/index.ts
frontend/src/components/SideBar/index.tsx
frontend/src/components/SideBar/style.tsx
frontend/src/pages/Admin/AdminAuth/index.tsx
frontend/src/pages/Admin/CustomerList/index.tsx
frontend/src/pages/Admin/EarnStamp/SelectCoupon/index.tsx
frontend/src/pages/Admin/EarnStamp/SelectCoupon/style.tsx
frontend/src/pages/Admin/EarnStamp/index.tsx
frontend/src/pages/Admin/EarnStamp/style.tsx
frontend/src/pages/Admin/ModifyCouponPolicy/CreatedType/index.tsx
frontend/src/pages/Admin/ModifyCouponPolicy/CreatedType/style.tsx
frontend/src/pages/Admin/ModifyCouponPolicy/index.tsx
frontend/src/pages/Admin/ModifyCouponPolicy/style.tsx
frontend/src/pages/Admin/RegisterCafe/style.tsx

[FE] fix: 카페등록 페이지 오류 해결

---

frontend/src/api/index.ts
frontend/src/components/SideBar/index.tsx
frontend/src/pages/Admin/AdminLogin/index.tsx
frontend/src/pages/Admin/AdminLogin/style.tsx
frontend/src/pages/RewardList/style.tsx

[FE] fix: token 고객 사장 바껴들어간 것 수정

---

frontend/src/api/get.ts
frontend/src/constants/index.ts
frontend/src/hooks/useCafeId.ts
frontend/src/hooks/useRedirectRegisterPage.ts
frontend/src/pages/Admin/CouponDesign/CustomCouponDesign/index.tsx
frontend/src/pages/Admin/CouponDesign/TemplateCouponDesign/index.tsx
frontend/src/pages/Admin/CouponDesign/hooks/useMutateCouponPolicy.ts
frontend/src/pages/Admin/CustomerList/index.tsx
frontend/src/pages/Admin/EarnStamp/index.tsx
frontend/src/pages/Admin/ManageCafe/index.tsx
frontend/src/pages/Admin/RegisterCafe/index.tsx
frontend/src/pages/Admin/RewardPage/index.tsx
frontend/src/pages/Admin/SelectCoupon/index.tsx
frontend/src/pages/EnterPhoneNumber/index.tsx

[FE] refactor: 하드코딩된 cafeId를 api 에서 불러온 값으로 변경한다. 

---

backend/build.gradle
backend/src/main/java/com/stampcrush/backend/api/manager/image/ManagerImageCommandApiController.java
backend/src/main/java/com/stampcrush/backend/application/manager/image/ManagerImageCommandService.java
backend/src/main/java/com/stampcrush/backend/config/WebMvcConfig.java
backend/src/main/java/com/stampcrush/backend/config/s3/S3Config.java
backend/src/main/java/com/stampcrush/backend/entity/image/ImageUploader.java
backend/src/main/java/com/stampcrush/backend/entity/image/S3ImageUploader.java
backend/src/main/resources/application-test.yml

[BE] feat: 이미지 업로드 기능 구현

---

frontend/src/pages/CouponList/Header/index.tsx
frontend/src/pages/CouponList/index.tsx

[FE] fix: 고객 모드 오류 수정

---

frontend/src/pages/Admin/ManageCafe/index.tsx
frontend/src/utils/index.ts

[FE] bug: 사장 모드의 내 카페 관리 탭에서 introduction 필드가 null 일 때의 상황을 처리한다

---

backend/build.gradle
backend/src/main/java/com/stampcrush/backend/api/GlobalExceptionHandler.java
backend/src/main/java/com/stampcrush/backend/api/manager/image/ManagerImageCommandApiController.java
backend/src/main/java/com/stampcrush/backend/application/manager/image/ManagerImageCommandService.java
backend/src/main/java/com/stampcrush/backend/config/WebMvcConfig.java
backend/src/main/java/com/stampcrush/backend/config/s3/S3Config.java
backend/src/main/java/com/stampcrush/backend/entity/image/ImageUploader.java
backend/src/main/java/com/stampcrush/backend/entity/image/S3ImageUploader.java
backend/src/main/java/com/stampcrush/backend/exception/ImageUploadFailException.java
backend/src/main/resources/application-test.yml

[BE] refactor: s3 수정

---

backend/src/main/java/com/stampcrush/backend/api/manager/image/ManagerImageCommandApiController.java
backend/src/main/java/com/stampcrush/backend/api/manager/image/response/ImageUrlResponse.java
backend/src/main/java/com/stampcrush/backend/entity/image/S3ImageUploader.java
backend/src/main/resources/application-test.yml

- prod / dev 나누어 사진 업로드
- 
closes #528

[BE] fix: 디렉터리 별 저장 기능 구현

---

frontend/src/api/get.ts
frontend/src/api/post.ts
frontend/src/constants/index.ts
frontend/src/hooks/useUploadImage.ts
frontend/src/pages/Admin/CouponDesign/ChoiceTemplate/index.tsx
frontend/src/types/api.ts
frontend/src/utils/index.ts

- 이미지 업로드 로직에 싣는 body가 json 타입이 아니라, 추상화된 api를 사용하지 않았습니다.
- 추가로 템플릿 뒷면이 올라가지 않는 이슈를 해결했습니다 !
closes #512

[FE] feat: 이미지 업로드 기능을 백엔드와 연동한다. 

---

frontend/src/api/get.ts
frontend/src/hooks/useRedirectPhoneNumberPage.ts
frontend/src/pages/Admin/AdminAuth/index.tsx
frontend/src/pages/MyPage/index.tsx
frontend/src/types/api.ts
frontend/src/types/index.ts

[FE] feat: 로그아웃 및 프로필 조회 기능 구현

---

frontend/src/pages/Admin/EarnStamp/SelectCoupon/index.tsx

[FE] fix: 스탬프 적립 페이지 렌더링 오류 해결

---

backend/src/main/java/com/stampcrush/backend/api/visitor/profile/VisitorProfilesFindApiController.java
backend/src/main/java/com/stampcrush/backend/api/visitor/profile/response/VisitorProfilesFindResponse.java
backend/src/main/java/com/stampcrush/backend/application/visitor/profile/VisitorProfilesFindService.java
backend/src/main/java/com/stampcrush/backend/application/visitor/profile/dto/VisitorProfileFindResultDto.java
backend/src/main/java/com/stampcrush/backend/repository/user/RegisterCustomerRepository.java
backend/src/test/java/com/stampcrush/backend/acceptance/VisitorProfileFindAcceptanceTest.java

[BE] feat: 고객의 프로필 정보를 조회해오는 API 를 구현한다

---

frontend/src/mocks/mockData.ts
frontend/src/pages/Admin/CouponDesign/ChoiceTemplate/style.tsx
frontend/src/pages/Admin/EarnStamp/SelectCoupon/index.tsx
frontend/src/pages/Admin/ManageCafe/index.tsx

[FE] fix: 스크롤이 안되는 오류 및 하드코딩 코드 제거

---

frontend/src/api/get.ts
frontend/src/components/SideBar/index.tsx
frontend/src/hooks/useIsLoggedIn.ts
frontend/src/pages/Admin/AdminLogin/index.tsx
frontend/src/pages/Admin/CustomerList/index.tsx
frontend/src/pages/MyPage/index.tsx

[FE] Hotfix: 헤더 추가, 리다이렉팅, 로그아웃 오류 해결

---

frontend/src/api/get.ts
frontend/src/api/post.ts

[FE] fix: 로컬스토리, api 명세와 불일치 오류 해결

---

frontend/src/pages/Admin/EarnStamp/SelectCoupon/index.tsx

[FE] fix: history API 전달하는 state 수정

---

frontend/src/api/delete.ts
frontend/src/api/get.ts
frontend/src/api/index.ts
frontend/src/api/patch.ts
frontend/src/api/post.ts

[FE] fix: bearer null 오류 해결

---

backend/src/main/java/com/stampcrush/backend/api/visitor/profile/VisitorProfilesCommandApiController.java
backend/src/main/java/com/stampcrush/backend/api/visitor/profile/request/VisitorProfilesPhoneNumberUpdateRequest.java
backend/src/test/java/com/stampcrush/backend/acceptance/VisitorProfilesCommandAcceptanceTest.java
backend/src/test/java/com/stampcrush/backend/acceptance/step/VisitorProfilesCommandStep.java

[BE] fix: Phone Number 수정 Request에 기본 생성자 추가

---

frontend/src/pages/Admin/EarnStamp/SelectCoupon/index.tsx

[FE] fix: 새 쿠폰 발급이 선택 안되는 문제

---

frontend/src/pages/Admin/EarnStamp/SelectCoupon/index.tsx

[FE] fix: coupons:[]일 때 대응

---

frontend/src/constants/index.ts
frontend/src/pages/Admin/RewardPage/index.tsx

[FE] fix: 리워드 사용 잘못된 api 요청 수정

---

frontend/src/pages/Admin/EarnStamp/SelectCoupon/index.tsx

[FE] fix: 기존 쿠폰이 쿠폰이 없는 경우 신규 쿠폰이 발급되지 않는 문제

---

frontend/src/pages/Admin/EarnStamp/SelectCoupon/index.tsx

[FE] fix: 쿠폰 발급 오류 해결

---

backend/src/main/java/com/stampcrush/backend/api/visitor/profile/response/VisitorProfilesFindResponse.java

[BE] fix: 고객 프로필 조회 api 반환값을 명세에 맞게 반환 수정

---

backend/src/main/java/com/stampcrush/backend/api/visitor/reward/response/VisitorRewardsFindResponse.java
backend/src/test/java/com/stampcrush/backend/api/visitor/reward/VisitorRewardsFindControllerTest.java

[FE] fix: Reward History data formatting 수정

---

frontend/src/pages/Admin/CouponDesign/ChoiceTemplate/index.tsx
frontend/src/pages/HistoryPage/StampHistory/index.tsx
frontend/src/types/api.ts

[FE] fix: api 응답 속성 잘못된 영문법 수정

---

backend/src/main/java/com/stampcrush/backend/api/visitor/visithistory/response/CustomerStampHistoriesFindResponse.java
backend/src/test/java/com/stampcrush/backend/api/docs/visitor/visithistory/VisitorVisitHistoryFindApiDocsControllerTest.java

[BE] fix: StampHistories 응답 명세 프론트와 통일

---

backend/src/main/java/com/stampcrush/backend/api/visitor/visithistory/response/CustomerStampHistoryFindResponse.java
backend/src/main/java/com/stampcrush/backend/application/visitor/visithistory/dto/CustomerStampHistoryFindResultDto.java
backend/src/test/java/com/stampcrush/backend/api/docs/visitor/visithistory/VisitorVisitHistoryFindApiDocsControllerTest.java

- 레오가 구현했던 API 중에서 날짜 formatting에 대한 로직이 service dto에 있어서 request dto로 옮겼음
closes

[BE] refactor: Request DTO로 날짜 formatting 코드 이동

---

frontend/src/pages/Admin/AdminAuth/index.tsx
frontend/src/pages/Admin/AdminLogin/index.tsx
frontend/src/pages/Admin/EnterPhoneNumber/Dialpad/index.tsx
frontend/src/pages/Auth/index.tsx
frontend/src/pages/CouponList/CouponDetail/index.tsx
frontend/src/pages/CouponList/CouponDetail/style.tsx
frontend/src/pages/CouponList/index.tsx
frontend/src/pages/InputPhoneNumber/index.tsx

[FE] fix: 전화번호 등록 버그 및 디자인 수정

---

frontend/src/pages/Admin/EnterPhoneNumber/Dialpad/style.tsx
frontend/src/pages/Admin/ManageCafe/TimeRangePicker/style.tsx
frontend/src/pages/CouponList/Coupon/style.tsx
frontend/src/pages/CouponList/Header/index.tsx
frontend/src/pages/MyPage/index.tsx
frontend/src/pages/MyPage/style.tsx

[FE] refactor: 마이페이지 디자인 수정

---

backend/src/main/java/com/stampcrush/backend/api/manager/cafe/ManagerCafeCouponSettingFindApiController.java

[BE] feat: 카페 이미지 반환 api작성

---

frontend/src/api/get.ts
frontend/src/pages/Admin/EarnStamp/SelectCoupon/index.tsx

[FE] fix: api 명세에 대응

---

backend/src/main/java/com/stampcrush/backend/api/manager/cafe/ManagerCafeCouponSettingFindApiController.java

[BE] feat: 카페 쿠폰 이미지 반환

---

frontend/src/pages/CouponList/CouponDetail/index.tsx
frontend/src/pages/CouponList/CouponDetail/style.tsx

[FE] fix: 쿠폰 상세보기 값 없을 때 예외 처리

---

frontend/src/pages/Admin/EarnStamp/SelectCoupon/index.tsx

[FE] fix: 방어 코드 추가

---

frontend/src/pages/Admin/EarnStamp/SelectCoupon/index.tsx

[FE] fix: 픽스2

---

frontend/src/pages/Admin/EarnStamp/SelectCoupon/index.tsx

[FE] fix: 스탬프 적립 페이지 오류

---

frontend/src/pages/Admin/EarnStamp/SelectCoupon/index.tsx
frontend/src/pages/Admin/EarnStamp/index.tsx

[FE] fix: 첫번째 페이지에서 쿠폰 정보 제거

---

frontend/src/pages/Admin/EarnStamp/index.tsx

[FE] fix: 쿼리 키 추가

---

backend/src/main/java/com/stampcrush/backend/config/RequestLoggingFilter.java
backend/src/main/resources/logback-spring.xml

- filter를 사용해 request url, auth정보 logging
closes

[BE] feat: request 정보 logging

---

backend/src/main/java/com/stampcrush/backend/application/manager/cafe/ManagerCafeCommandService.java

[BE] fix: 샘플 저장 하지 않게 변경

---

frontend/cypress/e2e/earnStamp.cy.ts
frontend/cypress/support/e2e.ts
frontend/src/mocks/handlers.ts
frontend/src/mocks/mockData.ts
frontend/src/pages/Admin/CustomerList/Customers/style.tsx

테스트 전략에 따라 몹 프로그래밍 진행하였습니다.
#599 closes

[FE] test: 스탬프 적립 시나리오를 기반으로 테스트를 작성한다.

---

frontend/src/api/index.ts
frontend/src/api/post.ts
frontend/src/constants/index.ts
frontend/src/pages/Login/index.tsx

**!!! 필독 !!!**
- 앞으로 로컬에서 개발 시, DEV 서버의 ip를 이용할 수 있게 되었습니다~!!
아래 변수를, `.env` 에 추가해주세요. 서버 주소는 슬랙 고정됨에서 확인할 수 있습니다!
```
REACT_APP_DEV_URL = {DEV 서버 주소}
```
closes #609

[FE] bug: DEV서버 운영에 따른 환경변수 사용을 변경한다. 

---

frontend/src/App.tsx
frontend/src/Router.tsx

- `Suspense` 옵션을 `false`로 변경하였습니다.
closes #616

[FE] bug: Suspense로 인한 오류를 해결한다.

---

frontend/src/api/index.ts
frontend/src/hooks/useDialPad.ts
frontend/src/pages/Admin/AdminLogin/index.tsx
frontend/src/pages/Admin/EarnStamp/SelectCoupon/index.tsx
frontend/src/pages/Admin/EarnStamp/index.tsx
frontend/src/pages/Admin/EnterPhoneNumber/Dialpad/index.tsx
frontend/src/pages/Admin/EnterPhoneNumber/index.tsx
frontend/src/pages/Admin/EnterPhoneNumber/style.tsx

[FE] feat: 스탬프 적립시 전화번호 입력 후 첫 적립임을 확인하는 Alert 추가

---

frontend/src/components/Template/CustomerTemplate/BottomTabBar/index.tsx
frontend/src/components/Template/CustomerTemplate/index.tsx

- `TabBar`의 렌더링 계층을 변경한다.
closes #634

[FE] refactor: `TabBar`의 렌더링 계층을 변경한다.

---

frontend/src/api/post.ts
frontend/src/hooks/useDialPad.ts
frontend/src/pages/Admin/EarnStamp/SelectCoupon/index.tsx
frontend/src/pages/Admin/EnterPhoneNumber/Dialpad/index.tsx
frontend/src/pages/Admin/RewardPage/index.tsx
frontend/src/utils/index.ts

[FE] refactor: 전화번호로 고객 조회 로직을 전화번호 입력페이지로 이동시킨다. (재Pr)

---

backend/build.gradle
backend/src/main/java/com/stampcrush/backend/entity/user/Customer.java
backend/src/main/resources/application-test.yml
backend/src/main/resources/db/migration/V1__init/V1__init.sql
backend/src/main/resources/db/migration/V1__init/V2__alter_customer.sql

[BE] feat: flyway로 스키마 변경 스크립트 작성 

---

backend/src/main/resources/db/migration/V1__init/V2__alter_customer.sql

[BE] fix: customer oauth_id type 수정

---

backend/src/main/resources/db/migration/V1__init/V3__delete_inheritance.sql

[BE] feat: dtype 컬럼 삭제 후 temporary_customer, register_customer 테이블 삭제 마이그레이션 스크립트 작성

---

backend/src/main/resources/db/migration/V1__init/V2__alter_customer.sql
backend/src/main/resources/db/migration/V1__init/V4__alter_customer_fix.sql

[BE] feat: V4 마이그레이션 스크립트 작성

---

backend/src/main/resources/db/migration/V1__init/V5__drop_table.sql

[BE] feat: drop table 마이그레이션 스크립트 작성

---

backend/src/main/java/com/stampcrush/backend/application/visitor/profile/dto/VisitorProfileFindByPhoneNumberResultDto.java
backend/src/main/java/com/stampcrush/backend/entity/user/Customer.java
backend/src/main/java/com/stampcrush/backend/entity/user/CustomerType.java
backend/src/test/java/com/stampcrush/backend/api/visitor/profile/VisitorProfilesFindApiControllerTest.java

- log PR 머지 하면서 CustomerType 버그 수정 전으로 덮어져서 다시 수정했습니다
closes #673

fix: customer type 버그 수정

---

backend/src/main/java/com/stampcrush/backend/auth/api/ManagerAuthController.java
backend/src/main/java/com/stampcrush/backend/auth/api/VisitorAuthController.java
backend/src/main/java/com/stampcrush/backend/auth/api/request/OAuthRegisterCustomerCreateRequest.java
backend/src/main/java/com/stampcrush/backend/auth/api/request/OAuthRegisterOwnerCreateRequest.java
backend/src/main/java/com/stampcrush/backend/auth/application/ManagerAuthService.java
backend/src/test/java/com/stampcrush/backend/acceptance/ManagerJoinAcceptanceTest.java
backend/src/test/java/com/stampcrush/backend/acceptance/VisitorLinkDataAcceptanceTest.java
backend/src/test/java/com/stampcrush/backend/acceptance/VisitorProfilesCommandAcceptanceTest.java
backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerJoinStep.java
backend/src/test/java/com/stampcrush/backend/acceptance/step/VisitorJoinStep.java

[BE] feat: 사장 회원가입/로그인 API (테스트 용도)

---

backend/src/main/java/com/stampcrush/backend/auth/api/ManagerAuthController.java
backend/src/main/java/com/stampcrush/backend/auth/api/VisitorAuthController.java
backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerJoinStep.java
backend/src/test/java/com/stampcrush/backend/acceptance/step/VisitorJoinStep.java

[BE] refactor: 회원가입/로그인 API URI 변경

---

backend/src/main/java/com/stampcrush/backend/auth/api/VisitorAuthController.java
backend/src/main/java/com/stampcrush/backend/auth/application/VisitorAuthService.java
backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerCafeCreateStep.java
backend/src/test/java/com/stampcrush/backend/acceptance/step/VisitorJoinStep.java

[BE] test: 테스트에서 사용하는 API 최신 스펙에 따라 변경

---

frontend/src/pages/Admin/EarnStamp/index.tsx
frontend/src/pages/Admin/EarnStamp/style.tsx
frontend/src/pages/Customer/CouponList/style.tsx

- 스탬프 적립 페이지에서 적립할 스탬프 개수에 따라 쿠폰에 추가적으로 스탬프가 찍히도록 하였습니다.
closes #703

[FE] feat: 스탬프 적립 페이지에서 적립할 스탬프 개수에 따라 렌더링한다.

---

frontend/src/components/Header/SubHeader/index.tsx
frontend/src/components/SideBar/index.tsx
frontend/src/pages/Admin/CustomerList/Customers/index.tsx
frontend/src/pages/Admin/CustomerList/hooks/useGetCustomers.ts
frontend/src/pages/Admin/CustomerList/index.tsx
frontend/src/pages/Customer/HistoryPage/HistoryPage.tsx
frontend/src/pages/Customer/HistoryPage/style.tsx
frontend/src/pages/Customer/MyPage/index.tsx

1. 사장모드 메인로고 클릭시 고객리스트 페이지로 이동
2. 사장모드 고객리스트 페이지 검색 기능 제거, 정렬 기능 오류(한박자씩 늦게 정렬되는 문제) 해결 
3. 고객리스트 페이지 useQuery 훅으로 분리
4. 고객모드 TabBar 생성에 따른 subHeader 라우팅 로직 수정
closes #685

[FE] refactor: 사용자 유치 전 다양한 버그를 해결한다. 

---

frontend/src/pages/Admin/EnterPhoneNumber/index.tsx
frontend/src/pages/Admin/EnterPhoneNumber/style.tsx

[FE] refactor: 개인정보 수집 및 이용 동의 개선

---

frontend/src/api/index.ts

[FE] fix: 잘못된 redirect url 변경

---

frontend/src/api/index.ts

- 라잇의 아이디어로 분기 처리를 구현하였습니다.
- 토큰 만료 + 로그아웃시 admin 페이지에 접근하면 중복으로 redirect이 되어 불필요하게 화면이 깜빡이는 부분이 있었는데, 분기를 넣어서 처리했어요.
-

[FE] feat: 요청에 따른 access token 분기처리

---

backend/src/main/java/com/stampcrush/backend/api/DummyController.java

[BE] feat: coupon 더미 데이터 컨트롤러

---

backend/src/main/java/com/stampcrush/backend/api/DummyController.java

[BE] fix: dummy URI 변경

---

backend/src/main/java/com/stampcrush/backend/config/RequestLoggingFilter.java
backend/src/main/resources/logback-spring.xml

[BE] feat: thread 정보 로깅

---

backend/src/main/java/com/stampcrush/backend/config/RequestLoggingFilter.java
backend/src/main/resources/logback-spring.xml

[BE] feat: thread loggin 수정

---

frontend/src/components/SideBar/index.tsx
frontend/src/components/SideBar/style.tsx

[FE] fix: 사장모드 로고가 사라지는 오류 트러블 슈팅

---

frontend/src/pages/Customer/InputPhoneNumber/hooks/useInputPhoneNumber.ts

fix: async로 수정

---

backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCafeFindAcceptanceTest.java
backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerCafeFindStep.java

[BE] feat: 카페 사장의 findAllCafes() 인수테스트 작성

---

backend/src/main/java/com/stampcrush/backend/api/visitor/profile/response/VisitorProfilesFindByPhoneNumberResponse.java
backend/src/main/java/com/stampcrush/backend/api/visitor/reward/response/VisitorRewardsFindResponse.java
backend/src/test/java/com/stampcrush/backend/acceptance/VisitorProfileFindAcceptanceTest.java
backend/src/test/java/com/stampcrush/backend/acceptance/VisitorRewardFindAcceptanceTest.java
backend/src/test/java/com/stampcrush/backend/acceptance/step/VisitorRewardFindStep.java

[BE] feat: 전화번호로 고객 프로필 조회 및 고객의 리워드 조회 테스트

---

backend/src/main/java/com/stampcrush/backend/api/manager/cafe/response/CafesFindResponse.java
backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCafeFindAcceptanceTest.java
backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCouponCommandAcceptanceTest.java
backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCouponFindAcceptanceTest.java
backend/src/test/java/com/stampcrush/backend/acceptance/VisitorVisitHistoryFindAcceptanceTest.java
backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerCafeFindStep.java
backend/src/test/java/com/stampcrush/backend/acceptance/step/VisitorVisitHistoriesFindStep.java

[BE] feat: Visitor Visit History 인수테스트 작성

---

backend/src/main/java/com/stampcrush/backend/auth/application/manager/ManagerOAuthLoginService.java
backend/src/main/java/com/stampcrush/backend/auth/application/visitor/VisitorOAuthLoginService.java
backend/src/main/java/com/stampcrush/backend/repository/user/CustomerRepository.java
backend/src/main/java/com/stampcrush/backend/repository/user/OwnerRepository.java
backend/src/test/java/com/stampcrush/backend/repository/user/OwnerRepositoryTest.java
backend/src/test/java/com/stampcrush/backend/repository/user/RegisterCustomerRepositoryTest.java

[BE] refactor: oauth 인증 반환값 변경해서 커버링 인덱스 사용할 수 있도록 변경

---

frontend/src/pages/Admin/EnterPhoneNumber/index.tsx
frontend/src/pages/Admin/EnterPhoneNumber/style.tsx
frontend/src/pages/Customer/InputPhoneNumber/hooks/usePostCustomerPhoneNumber.tsx

[FE] fix: 하이픈 제거 로직 및 개인정보 수집기간 칼럼 추가

---

frontend/src/components/Input/index.tsx

- Input이 정상동작하지 않는 문제는 이전의 코드로 롤백하여 복구하였습니다.
closes

[FE] fix: `Input` 속성 수정

---

frontend/src/components/Input/index.tsx

[FE] fix: `Input` 오류 수정

---

backend/src/main/java/com/stampcrush/backend/auth/application/util/AuthTokensGenerator.java

[BE] feature: Access Token 만료시간 24시간으로 설정

---

backend/src/main/resources/db/migration/V6__delete_customer.sql

[BE] fix: Flyway 스크립트 수정 (Coupon Table delete 칼럼 추가 부분 삭제)

---

backend/src/main/resources/db/migration/V6__delete_customer.sql
backend/src/main/resources/db/migration/V7__alter_delete.sql

[BE] fix: Flyway 스크립트 수정

---

backend/src/main/resources/db/migration/V8__alter_delete_column_type.sql

[BE] fix: deleted column 의 type 을 bit(1) 로 변경하는 스크립트 추가

---

frontend/src/components/Header/SubHeader/style.tsx
frontend/src/pages/Admin/EnterPhoneNumber/Dialpad/style.tsx
frontend/src/pages/Admin/EnterPhoneNumber/index.tsx
frontend/src/pages/Admin/EnterPhoneNumber/style.tsx

[FE] fix: 아이패드 환경 스크롤 대처

---

frontend/src/components/Header/SubHeader/style.tsx
frontend/src/constants/index.ts
frontend/src/pages/Customer/MyPage/index.tsx
frontend/src/pages/Customer/MyPage/style.tsx

[FE] feat: 마이페이지에 만족도 조사 링크를 추가한다.

---

backend/src/main/java/com/stampcrush/backend/api/manager/owner/ManagerCommandApiController.java
backend/src/main/java/com/stampcrush/backend/api/manager/owner/request/OwnerCreateRequest.java
backend/src/main/java/com/stampcrush/backend/api/manager/owner/request/OwnerLoginRequest.java
backend/src/main/java/com/stampcrush/backend/application/manager/owner/ManagerCommandService.java
backend/src/main/java/com/stampcrush/backend/application/manager/owner/dto/OwnerCreateDto.java
backend/src/main/java/com/stampcrush/backend/application/manager/owner/dto/OwnerLoginDto.java
backend/src/main/java/com/stampcrush/backend/application/manager/owner/util/PasswordEncryptor.java
backend/src/main/java/com/stampcrush/backend/application/manager/owner/util/PasswordValidator.java
backend/src/main/java/com/stampcrush/backend/auth/application/util/AuthTokensGenerator.java
backend/src/main/java/com/stampcrush/backend/config/WebMvcConfig.java
backend/src/main/java/com/stampcrush/backend/entity/user/Owner.java
backend/src/main/java/com/stampcrush/backend/exception/LoginIdBadRequestException.java
backend/src/main/java/com/stampcrush/backend/exception/PasswordBadRequestException.java
backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCommandAcceptanceTest.java
backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerCreateStep.java
backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerLoginStep.java
backend/src/test/java/com/stampcrush/backend/api/manager/owner/ManagerCommandApiControllerTest.java
backend/src/test/java/com/stampcrush/backend/application/manager/owner/ManagerCommandServiceTest.java
backend/src/test/java/com/stampcrush/backend/application/manager/owner/util/PasswordValidatorTest.java

[BE] feat: cafe owner can login by id and password.

---

backend/src/main/java/com/stampcrush/backend/api/visitor/profile/VisitorCancelMembershipCommandApiController.java
backend/src/test/java/com/stampcrush/backend/api/docs/DocsControllerTest.java
backend/src/test/java/com/stampcrush/backend/api/docs/visitor/profile/VisitorCancelMembershipCommandApiDocsController.java
backend/src/test/java/com/stampcrush/backend/api/docs/visitor/profile/VisitorCancelMembershipCommandApiDocsControllerTest.java

[BE] test: VisitorCancelMembershipCommandApiController swagger용 테스트 작성

---

backend/src/main/java/com/stampcrush/backend/application/manager/cafe/ManagerCafeCommandService.java
backend/src/main/java/com/stampcrush/backend/application/manager/cafe/SampleImages.java

- https://dnv0gl9rzyzod.cloudfront.net/prod/basic_coupon_front_image.jpg 이거로 변경했습니다 
closes

[BE] feat: 카페 등록 시 쿠폰 앞면 기본 이미지를 수정한다

---

backend/src/main/java/com/stampcrush/backend/entity/reward/Reward.java
backend/src/test/java/com/stampcrush/backend/acceptance/ManagerRewardCommandAcceptanceTest.java
backend/src/test/java/com/stampcrush/backend/entity/reward/RewardTest.java

- 임시회원도 리워드를 사용할 수 있게끔 변경했습니다. 
closes #808

[BE] refactor: 임시회원이 리워드를 사용할 수 있다.

---

frontend/src/pages/Admin/CustomerList/index.tsx
frontend/src/pages/Admin/CustomerList/style.tsx

서비스 런칭 초반에 고객이 없을 경우가 길 것 같아서 해당 문제상황을 빠르게 대응해야할 것 같습니다
월요일에 함께 머지 부탁드립니다!
closes #797

[FE] fix: 탭바가 있으면서 고객이 없을때의 상황을 대응한다

---

backend/src/main/java/com/stampcrush/backend/application/visitor/profile/VisitorCancelMembershipCommandService.java

- VisitorCancelMembershipCommandService 에 트랜잭션 어노테이션 추가했습니다.
closes

[BE] fix: 회원탈퇴 service 레이어에 트랜잭션 어노테이션 추가

---

backend/src/main/java/com/stampcrush/backend/api/manager/coupon/ManagerCouponCommandApiController.java
backend/src/main/java/com/stampcrush/backend/api/manager/coupon/request/StampCreateRequest.java
backend/src/main/java/com/stampcrush/backend/application/manager/coupon/dto/StampCreateDto.java
backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCouponCommandAcceptanceTest.java
backend/src/test/java/com/stampcrush/backend/repository/user/OwnerRepositoryTest.java

[BE] fix: 스탬프 적립 0개를 막는다. 

---

backend/src/main/java/com/stampcrush/backend/application/manager/coupon/ManagerCouponCommandService.java
backend/src/main/java/com/stampcrush/backend/application/manager/event/StampAccumulatingEventHandler.java
backend/src/main/java/com/stampcrush/backend/application/manager/event/StampCreateEvent.java

[BE] hotfix: 스탬프 적립 시 슬랙 알림에 카페이름을 추가한다

---

backend/src/main/resources/db/migration/V10__set-index.sql

현재 사용하고 있는 인덱스를 데이터베이스에 직접 명령어를 입력하는 방식 말고, Flyway를 사용해서 재설정하려고 합니다. 충돌을 방지하기 위해서 데이터베이스 내에서는 인덱스를 미리 제거한 상태입니다.
```sql
create index index_phone_number on customer (phone_number);
create index index_oauth_id_oauth_provider on customer (oauth_id, oauth_provider);
```
위 내용이 반영된 후에 인덱스는 아래와 같이 설정될 것입니다.
```bash
mysql> show index from customer;
+----------+------------+-------------------------------+--------------+----------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+------------+
| Table    | Non_unique | Key_name                      | Seq_in_index | Column_name    | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment | Visible | Expression | …
```

[BE] feat: 인덱스 설정 스크립트 작성

---

frontend/src/pages/Customer/MyPage/index.tsx
frontend/src/pages/Customer/RewardList/index.tsx

레고와 저 pr 병합 중 쓰지 않는 모듈을 삭제를 안해서 빌드 에러가 났습니다. 
closes

[FE] fix: 병합 중 생긴 에러 수정

---

backend/src/main/java/com/stampcrush/backend/entity/visithistory/VisitHistory.java
backend/src/main/resources/db/migration/V11__add_delete_visit_history.sql

- visit history 엔티티에 소프트 딜리트 설정 추가
- flyway 로 visit history 테이블에 deleted 컬럼 추가
closes #839

[BE] fix: VisitHistory soft delete 추가

---

backend/Dockerfile-dev
backend/Dockerfile-prod
backend/src/main/java/com/stampcrush/backend/api/HealthCheckApiController.java

- 무중단 배포를 위한 Dockerfile 생성과 HealthCheckController 를 생성했습니다
closes

[BE] feat: Dockerfile 생성, HealthCheckController 생성

---

frontend/src/components/Stepper/index.tsx

[FE] fix: 스탬프 적립 0개 막기

---

frontend/src/components/Template/CustomerTemplate/BottomTabBar/index.tsx
frontend/src/components/Template/CustomerTemplate/BottomTabBar/style.tsx
frontend/src/components/Template/CustomerTemplate/index.tsx
frontend/src/components/Template/index.tsx
frontend/src/components/Template/style.tsx
frontend/src/pages/Admin/AdminLogin/style.tsx
frontend/src/pages/Admin/CustomerList/Customers/style.tsx
frontend/src/pages/Admin/CustomerList/style.tsx
frontend/src/pages/Admin/EarnStamp/index.tsx
frontend/src/pages/Admin/EarnStamp/style.tsx
frontend/src/pages/Admin/EnterPhoneNumber/Dialpad/style.tsx
frontend/src/pages/Admin/EnterPhoneNumber/style.tsx
frontend/src/pages/Admin/RewardPage/index.tsx
frontend/src/pages/Admin/RewardPage/style.tsx

[FE] refactor: 사장모드의 반응형을 구현한다(for 글렌)

---

frontend/package.json
frontend/src/pages/Customer/CouponList/components/FlippedCoupon/index.tsx

- 배포한 react-turnable-component를 사용하였습니다.
- 기존의 코드를 최대한 바꾸지않고, sideEffect를 거치지 않은 방향으로 리팩터링 함께 진행하였습니다. 
함께 프로그래밍 하였으므로, 한번씩만 더블체크 해주시기 바랍니다~ ^^

[FE] feat: 최종 데모데이 요구사항을 반영한다.

---

README.md

- 작성 중
- 추가하고 싶은 거 있으면 이 풀리퀘에 추가해주시거나 코멘트로 달아주세요
closes #866

[ALL] (작성중) docs: README 를 예쁘게 꾸민다 🌸

---

.github/workflows/backend-dev-cd.yml

[BE] infra: create backend-dev-cd.yml

---

.github/workflows/backend-dev-cd.yml

[BE] fix: 백틱 제거

---

.github/workflows/backend-prod-cd.yml

[BE] feat: 운영 서버 깃허브 액션 pipeline 생성

---

.github/workflows/backend-dev-cd.yml

[BE] fix: 불필요한 설정 제거

---

.github/workflows/backend-prod-cd.yml

[BE] fix: 불필요한 prod cd 설정 제거

---

frontend/src/components/Stepper/index.tsx
frontend/src/components/Stepper/style.tsx
frontend/src/pages/Admin/EarnStamp/index.tsx

↑: 숫자 +1
↓: 숫자 -1
Enter: 적립
closes #890

[FE] feat: 스탬프 적립을 키패드로 조작 가능하게 한다. 

---

frontend/src/pages/Customer/CouponList/components/CafeInfo/style.tsx

[FE] fix: 빠진 모듈 추가

---

frontend/src/pages/Customer/CouponList/components/CafeInfo/style.tsx

[ALL] fix: 프론트엔드 버그를 수정한다.

---

backend/src/main/java/com/stampcrush/backend/entity/cafe/CafeCouponDesign.java
backend/src/main/java/com/stampcrush/backend/entity/cafe/CafePolicy.java
backend/src/main/resources/db/migration/V13__add_is_activate.sql

[BE] feat: cafe_coupon_design, cafe_policy 테이블에 isActivate 필드 추가

---

backend/src/main/resources/db/migration/V15__alter_is_active_type.sql
backend/src/main/resources/db/migration/V16__update_is_active.sql

[BE] feat: cafe coupon design is active 필드 DML 스크립트 + 타입 변경

---

backend/src/main/resources/db/migration/V18__update_coupon_new_column_ids.sql

[BE] feat: cafe_coupon_design_id, cafe_policy_id 값 추가 (DML 스크립트)

---

backend/src/main/java/com/stampcrush/backend/application/manager/cafe/ManagerCafeCouponSettingFindService.java
backend/src/main/java/com/stampcrush/backend/application/manager/cafe/dto/CafeCouponSettingFindResultDto.java
backend/src/main/java/com/stampcrush/backend/application/manager/coupon/ManagerCouponCommandService.java
backend/src/main/java/com/stampcrush/backend/application/visitor/coupon/VisitorCouponFindService.java
backend/src/main/java/com/stampcrush/backend/application/visitor/coupon/dto/CustomerCouponFindResultDto.java
backend/src/main/java/com/stampcrush/backend/auth/api/VisitorAuthController.java
backend/src/main/java/com/stampcrush/backend/entity/cafe/CafeCouponDesign.java
backend/src/main/java/com/stampcrush/backend/entity/cafe/CafePolicy.java
backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
backend/src/main/java/com/stampcrush/backend/repository/cafe/CafeStampCoordinateRepository.java
backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCouponCommandAcceptanceTest.java
backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCouponFindAcceptanceTest.java
backend/src/test/java/com/stampcrush/backend/application/manager/coupon/ManageCouponCommandServiceTest.java
backend/src/test/java/com/stampcrush/backend/application/manager/coupon/ManagerCouponFindServiceTest.java
backend/src/test/java/com/stampcrush/backend/application/visitor/coupon/VisitorCouponFindServiceTest.java
backend/src/test/java/com/stampcrush/backend/entity/coupon/CouponTest.java
backend/src/test/java/com/stampcrush/backend/fixture/CafeCouponDesignFixture.java
backend/src/test/java/com/stampcrush/backend/fixture/CouponDesignFixture.java
backend/src/test/java/com/stampcrush/backend/fixture/CouponFixture.java
backend/src/test/java/com/stampcrush/backend/repository/coupon/CouponRepositoryTest.java
backend/src/test/java/com/stampcrush/backend/repository/coupon/CouponRepositoryTest2.java
backend/src/test/java/com/stampcrush/backend/repository/coupon/CouponStampCoordinateRepositoryTest.java

[BE] feat: Coupon에서 couponDesign, couponPolicy 엔티티 의존성 제거 

---

backend/src/main/resources/db/migration/V19__alter_fk_on_coupon.sql

[BE] fix: 스크립트 롤백 (FK 설정 관련 에러)

---

backend/Dockerfile-dev

[BE] chore: Dockerfile-dev에서 프로필 설정 제거

---

backend/src/main/resources/application-dev2.yml

[BE] chore: dev2 프로필 설정

---

backend/Dockerfile-dev2.yml

[BE] chore: Dockerfile 추가

---

.github/workflows/backend-dev-cd.yml

[BE] chore: dev cd 파이프라인에서 Dockerfile-dev2로 변경
