woowacourse-teams/2023-stamp-crush

- frontend/src/components/SideBar/SideBar.style.tsx
- frontend/src/components/SideBar/index.tsx
close #11 
- 윤생의 `TapBar`를 상당부분 참고하였습니다.😅
- `useLocation`을 사용하여 현재 페이지의 `pathname`과 외부에서 주입받는 `value`를 비교합니다. 이를 통해 현재 페이지에 해당하는 네비게이션 바의 색상이 변경됩니다.
- 꺽쇠 부분은 `react-icons` 라이브러리를 사용하려다 현재는 css로 구현해둔 상태입니다. `react-icons`에 도입에 대한 이야기도 나누었으면 좋겠습니다.
`props`의 `options`로 
```typescript
export const routingList = [
{ key: '내 카페 등록', value: '/register-cafe' },
{ key: '내 카페 관리', value: '/manage-cafe' },
{ key: '고객 목록', value: '/' },
];
```
이런 형태의 배열을 넘겨주면 됩니다!
라우팅에 따라 사이드바의 background 색상이 변경되는 것을 확인할 수 있습니다.
> [FE] `SideBar` 컴포넌트 생성

- frontend/src/Router.tsx
- frontend/webpack.common.js
close #34 
webpack.common.js 파일에
```javascript
module.exports = {
...
output:{
...
publicPath: '/',
...
}
...
}
```
추가했더니 해결되었습니다!
https://stackoverflow.com/questions/75391508/react-router-dom6-3-0-does-not-render-child-components
> [FE] createBrowserRouter 내에서 children의 라우팅이 되지 않는 문제

- frontend/src/components/Dialpad/Dialpad.style.tsx
- frontend/src/components/Dialpad/index.tsx
- frontend/src/constants/index.ts
- frontend/src/hooks/useDialPad.ts
- frontend/src/pages/EnterPhoneNumber/index.tsx
close #15
- 키패드로 클릭, input 입력 통합하여 작동합니다.
- 기본값은 '010-'으로 정해져있고 지워지지 않습니다.
- 다양한 상수와 정규식들을 어디서 관리하면 좋을지 토의해봐야할 것 같습니다. 
- 제가 떠올릴 수 있는 방어로직은 다 구현한 상태인데, 혹시나 버그 발견하시고 알려주시면 감사하겠습니다.
> [FE] DialPad component 구현

- backend/src/main/java/com/stampcrush/backend/api/reward/RewardApiController.java
- backend/src/main/java/com/stampcrush/backend/api/reward/dto/request/RewardFindRequest.java
- backend/src/main/java/com/stampcrush/backend/api/reward/dto/request/RewardUsedUpdateRequest.java
- backend/src/main/java/com/stampcrush/backend/api/reward/dto/response/RewardFindResponse.java
- backend/src/main/java/com/stampcrush/backend/api/reward/dto/response/RewardsFindResponse.java
- backend/src/main/java/com/stampcrush/backend/application/reward/RewardService.java
- backend/src/main/java/com/stampcrush/backend/application/reward/dto/RewardFind.java
- backend/src/main/java/com/stampcrush/backend/application/reward/dto/RewardFindResult.java
- backend/src/main/java/com/stampcrush/backend/application/reward/dto/RewardUsedUpdate.java
- backend/src/main/java/com/stampcrush/backend/entity/cafe/Cafe.java
- backend/src/main/java/com/stampcrush/backend/entity/reward/Reward.java
- backend/src/main/java/com/stampcrush/backend/entity/user/Customer.java
- backend/src/main/java/com/stampcrush/backend/entity/user/Owner.java
- backend/src/main/java/com/stampcrush/backend/entity/user/RegisterCustomer.java
- backend/src/main/java/com/stampcrush/backend/entity/user/TemporaryCustomer.java
- backend/src/main/java/com/stampcrush/backend/repository/reward/RewardRepository.java
- backend/src/main/java/com/stampcrush/backend/repository/user/RegisterCustomerRepository.java
- backend/src/main/java/com/stampcrush/backend/repository/user/TemporaryCustomerRepository.java
- backend/src/main/java/com/stampcrush/backend/reward-request.http
- backend/src/test/java/com/stampcrush/backend/application/reward/RewardServiceTest.java
- backend/src/test/java/com/stampcrush/backend/entity/reward/RewardTest.java
- 등록회원, 임시회원의 레포지토리 생성
- 카페, 사장 생성자 추가
- 리워드 사용 기능 구현
- 일단 주기를 짧게 가져가려고 리워드 사용 기능만 추가했습니다 !
- `RewardApiController`, `RewardService`, `Reward` 와 이에 관련된 테스트 위주로 주로 보시면 될 것 같아요!
- 패키지 구조는 일단 제 방식대로 했는데 여러분과의 협의가 필요합니다 !!
- 특히 `Request`, `Response`의 경우 여러계층에 의존적이지 않으므로, `api` 패키지 밑에 두었습니다.
- 메서드명과 클래스명에 대한 고민을 많이 했습니다. (추천받습니다)
- 현재 인수테스트는 다른 기능들(회원가입)이 추가되지 않고 Inmemory로 쓰기 때문에 매번 초기화되며 인증방식의 미결정으로 인해 구현하지 않았습니다.
- 테스트는 Inmemory h2 database로 쓰시는지 local h2를 쓰시는지 궁금하네요 ㅎㅎ (경험공유해주시면 감사합니다)
- `application.yml` 파일을 수정했는데 따로 올리지는 않았습니다 ! (클론받아서 돌려보시면 아마.. 안돌아가실것 같아요) 
**Header**
```http
PATCH /customers/{customerId}/rewards/{rewardId} 
Header: owner 
```
**Body**
```json
{
"cafeId": 1,
"used": "true"
}
```
**Header**
```http
HTTP/1.1 200 OK
```
**Body**
None
**Header**
```http
GET …
```
> [BE] feat: 리워드 사용 및 조회 기능을 구현한다

- backend/src/main/java/com/stampcrush/backend/controller/CustomerController.java
- backend/src/main/java/com/stampcrush/backend/entity/user/Customer.java
- backend/src/main/java/com/stampcrush/backend/entity/user/RegisterCustomer.java
- backend/src/main/java/com/stampcrush/backend/entity/user/TemporaryCustomer.java
- backend/src/main/java/com/stampcrush/backend/repository/user/CustomerRepository.java
- backend/src/main/java/com/stampcrush/backend/service/CustomerResponse.java
- backend/src/main/java/com/stampcrush/backend/service/CustomerService.java
- backend/src/main/java/com/stampcrush/backend/service/CustomersResponse.java
- backend/src/main/java/com/stampcrush/backend/service/TemporaryCustomerRequest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/CustomerIntegrationTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/IntegrationTest.java
- 전화번호로 고객을 조회하는 API 를 작성했습니다
- 임시 고객을 생성하는 API 를 구현했습니다
```javascript
{
"customer": [
{
"id": 1,
"nickname": "윤생1234",
"phoneNumber": "01023456778"
}
]
}
```
가 명세이나 
```javascript
[
{
"id": 1,
"nickname": "윤생1234",
"phoneNumber": "01023456778"
}
]
```
형식으로 반환하게 바꾸면 어떨까요?? (key 값을 customer 라고 이름을 붙여주려면 Response 의 필드에 List\<CustomerResponse\> 가 들어가는 Response 를 하나 더 구현해야 해서 불필요하다고 느껴졌습니다)
- 코드를 작성하다보니 전화번호에 맞는 Customer 가 있으면 해당 Customer만 보내주고 없으면 인증이 안되었다고 봐도 될 것 같아CustomerNotFoundException 인 에러를 던지는 편이 낫지 않을지 의견을 제시합니다
(현재 주석처리 해둔 코드의 반환타입을 CustomerResponse 로 하고, Customer 를 못찾았을때 해당 커스텀 예외를 던지는 방향)
- Header의 Authorization 부분에 Owner 의 인증 정보가 들어오고 Owner 가 아니면 고객 조회를 못하는 것을 추가로 구현해야 합니다
- controller -> service 로 리퀘스트를 넘길 때 따로 Dto 를 사용하지 않고 그냥 String 으로 핸드폰 번호를 보냈습니다. 우리 서비스는 핸드폰 번호만 있어도 임시 …
> [BE] feat: 전화번호로 고객을 조회한다/ 임시 고객을 생성한다

- backend/src/main/java/com/stampcrush/backend/api/CouponController.java
- backend/src/main/java/com/stampcrush/backend/application/coupon/CouponService.java
- backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CafeCustomerInfoResponseDto.java
- backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CafeCustomersResponseDto.java
- backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CustomerUsingCouponResponseDto.java
- backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
- backend/src/main/java/com/stampcrush/backend/entity/coupon/CouponPolicy.java
- backend/src/main/java/com/stampcrush/backend/entity/coupon/Stamp.java
- backend/src/main/java/com/stampcrush/backend/entity/user/Customer.java
- backend/src/main/java/com/stampcrush/backend/entity/user/RegisterCustomer.java
- backend/src/main/java/com/stampcrush/backend/entity/user/TemporaryCustomer.java
- backend/src/main/java/com/stampcrush/backend/repository/coupon/CouponRepository.java
- backend/src/test/java/com/stampcrush/backend/application/coupon/CouponServiceTest.java
- backend/src/test/java/com/stampcrush/backend/entity/coupon/CouponTest.java
- backend/src/test/java/com/stampcrush/backend/repository/coupon/CouponRepositoryTest.java
- Coupon의 stamp개수를 쉽게 조회하기 위해 Stamp와 양방향 연관관계를 설정했습니다.
- 해당 기능이 고객 정보, 쿠폰 정보, 스탬프 정보를 모두 반환하는 기능이라 패키지 구조를 고민해봤습니다.
- 대부분의 정보를 조회하기 위해선 Coupon을 중심으로 join이 발생했기 때문에 coupon패키지로 정했습니다.
- 기존 엔티티에서 Coupon과 CouponPolicy연관관계가 없어서 이를 추가했습니다.
- Coupon이 Customer, CouponPolicy, CouponDesign, Cafe와 연관관계가 있어서 테스트하기 위한 사전 데이터를 추가하는 코드가 상당히 길어졌습니다..
- 그래서 이 연관관계를 꼭 객체로 해야하는지에 대해서 한 번 얘기해보면 좋을 것 같습니다! id로 풀 수도 있다고 하더라구요. 관련 세미나 영상 링크 걸어놓겠습니다. 영상이 길긴한데 보면 도움이 많이 될 것 같아요 ㅎ
- [우아한 객체지향 세미나](https://www.youtube.com/watch?v=dJ5C4qRqAgA&t=3956s)
- `현재 스탬프 쌓고 있는 쿠폰 정보 조회 구현`에서 해당 쿠폰이 이전 정책인지 알려주는 `isPrevious`를 구하기 위해 노력해봤는데, 현재 저희 ERD구조에서는 시간이 조금 걸릴 것 같아서 일단 false로 고정했습니다.
- 해당 부분은 시간이 조금 더 필요할 것 같아요..
- Controller에서 외부로 반환하는 DTO의 경우 제대로 동작하는지 확인해보기 위해선 관련 엔티티에 모든 정보를 다 넣어야하기 때문에 우선 service에서 반환된 DTO를 그대로 반환하게 …
> [BE] feat: 카페의 고객 목록 조회, 현재 스탬프 쌓고 있는 쿠폰 정보 조회 구현

- backend/src/main/java/com/stampcrush/backend/exception/BadRequestException.java
- backend/src/main/java/com/stampcrush/backend/exception/ForbiddenException.java
- backend/src/main/java/com/stampcrush/backend/exception/NotFoundException.java
- backend/src/main/java/com/stampcrush/backend/exception/StampCrushException.java
- backend/src/main/java/com/stampcrush/backend/exception/UnAuthorizationException.java
- 커스텀 예외 5개에 생성자 한개 추가했음.
- 이후에 있을 리팩터링을 위해서 빠른 머지가 필요함
closes #128
> [BE] feat: 커스텀 예외에 String만을 파라미터로 받는 생성자 추가

- frontend/src/Router.tsx
- frontend/src/components/Dialpad/Dialpad.style.tsx
- frontend/src/components/Template/Template.style.tsx
- frontend/src/pages/EnterPhoneNumber/index.tsx
- frontend/src/pages/EnterPhoneNumber/style.tsx
- 카페 사장님만이 전화번호를 입력할 수 있다는 플로우 하에 고객이 개인정보 제공 동의 체크박스를 체크할 수 없기 때문에 
개인정보 제공동의 컴포넌트 구현을 보류하였습니다.
close #13
> [FE] feat: 전화번호 입력 페이지 레이아웃 구현

- frontend/src/components/SelectBox/index.tsx
- 컴포넌트 내부에 있는 상태 로직을 props로 빼 내었습니다.
주말 잘 보내세요~~
closes #73
> [FE] refactor: 상태 로직을 컴포넌트 내부가 아닌 props로 이전

- frontend/package.json
- frontend/src/pages/Admin/RegisterCafe/index.tsx
- frontend/src/pages/Admin/RegisterCafe/style.tsx
> [FE] feat: 카페 등록 페이지에 도로명 주소 검색 API를 추가한다. 

- backend/src/main/java/com/stampcrush/backend/api/cafe/CafeApiController.java
- backend/src/main/java/com/stampcrush/backend/api/cafe/request/CafeCreateRequest.java
- backend/src/main/java/com/stampcrush/backend/application/cafe/CafeService.java
- backend/src/main/java/com/stampcrush/backend/application/cafe/dto/CafeCreateDto.java
- backend/src/main/java/com/stampcrush/backend/entity/cafe/Cafe.java
- backend/src/test/java/com/stampcrush/backend/application/cafe/CafeServiceTest.java
- 카페 등록 API 요청 스펙을 변경한다.
``` json
POST /cafes HTTP/1.1
{
"businessRegistrationNumber": "101-3852-97"
"name": "우아한커피",
"roadAddress": "서울시 송파구 올림픽0로 35다길",
"detailAddress": "루터회관 14층"
}
```
- 요청 스펙, 서비스에 넘기는 스펙, 카페 생성자 추가만 되었습니다 ^^
closes #113
> [BE] fix: 카페 등록 API 수정한다

- backend/src/main/java/com/stampcrush/backend/api/coupon/response/CustomerAccumulatingCouponFindResponse.java
- backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CustomerAccumulatingCouponFindResultDto.java
- backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
- backend/src/test/java/com/stampcrush/backend/application/coupon/CouponServiceTest.java
- 고객이 카페에서 적립중인 쿠폰의 maxStampCount데이터를 추가했습니다.
- 기존 테스트코드인 `존재O_현재_스탬프를_모으고_있는_쿠폰_정보를_조회한다`에서 새로운 쿠폰 정책을 만들어 기존 정책과 다른 maxStampCount를 생성해서 검증하는 방식으로 테스트 코드를 수정했습니다.
- 이 부분은 제가 실수로 PR #190 에서 분기를 따지 못했는데요.. 변경 사항은 되게 적습니다.
1. Coupon엔티티의 getCouponMaxStampCount메서드 추가
2. CustomerAccumulatingCouponFindResponse에서 maxStampCount설정하는 부분 상수 고정이 아닌 parameter.getMaxStampCount()로 변경
3. CustomerAccumulatingCouponFindResultDto도 2번과 마찬가지로 수정
- 혹시 충돌나면 위 3가지 부분만 봐주시면 됩니다!
closes #163
> [BE] feat: 현재 적립중인 쿠폰 데이터에 maxStampCount를 추가한다

- .github/workflows/backend_ci.yml
- github action ci 트리거 조건에서 push 조건 삭제
- PR 생성 후 추가 push 동작 시 워크 플로우 동작 다시 하는거 확인했습니다
closes
> [BE] feat: github action ci 트리거 조건에서 push 조건 삭제

- backend/src/main/java/com/stampcrush/backend/api/cafe/SampleCouponImage.java
- backend/src/main/java/com/stampcrush/backend/application/cafe/CafeService.java
- backend/src/test/java/com/stampcrush/backend/application/cafe/CafeServiceTest.java
구현 기능
```java
SampleFrontImage defaultSampleFrontImage = findDefaultSampleFrontImage();
SampleBackImage defaultSampleBackImage = findDefaultSampleBackImage();
SampleStampImage defaultSampleStampImage = findDefaultSampleStampImage();
```
현재 이렇게 샘플에 대한 내용을 직접 순회해서 찾고 있습니다.
```java
private SampleFrontImage findDefaultSampleFrontImage() {
List<SampleFrontImage> sampleFrontImages = sampleFrontImageRepository.findAll();
if (sampleFrontImages.isEmpty()) {
throw new IllegalArgumentException("저장된 샘플 앞면 이미지가 없습니다.");
}
return sampleFrontImages.get(0);
}
```
하지만, 이미지가 더미데이터로 저장되지 않은 경우에 에러가 발생하고 있습니다.
하드코딩으로 변경한다.
하지만, 이후에 더 좋은 방법을 찾아야 할 것 같다.
빠른 머지 부탁드려요!
closes #239
> [BE] refactor: Sample Coupon Default Image 순회 로직에서 하드코딩으로 변경

- frontend/src/Router.tsx
- frontend/src/api/get.ts
- frontend/src/custom.d.ts
- frontend/src/mocks/handlers.ts
- frontend/src/mocks/mockData.ts
- frontend/src/pages/CouponList/Coupon/index.tsx
- frontend/src/pages/CouponList/Coupon/style.tsx
- frontend/src/pages/CouponList/index.tsx
- frontend/src/pages/CouponList/style.tsx
- frontend/src/style/keyframes.ts
- 현재 쿠폰 리스트 부분만 구현되어있습니다.
레고와 페어프로그래밍하였습니다!
해당 페이지가 머지된 후에는 
추후에 고객모드 Header와, 레고가 만든 ProgressBar를 페이지에 넣어서 구현하면 될 듯합니다.
closes #220 #205
> [FE] feat: 쿠폰리스트 컴포넌트 및 페이지 구현

- backend/src/main/java/com/stampcrush/backend/api/cafe/CafeApiController.java
- backend/src/main/java/com/stampcrush/backend/api/cafe/CafeCouponSettingApiController.java
- backend/src/main/java/com/stampcrush/backend/api/coupon/CouponApiController.java
- backend/src/main/java/com/stampcrush/backend/api/customer/CustomerApiController.java
- backend/src/main/java/com/stampcrush/backend/api/reward/RewardApiController.java
- backend/src/main/java/com/stampcrush/backend/api/sample/SampleCouponApiController.java
- backend/src/test/java/com/stampcrush/backend/acceptance/CafeCouponSettingIntegrationTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/CustomerIntegrationTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/SampleCouponIntegrationTest.java
- 2차 데모데이 시 구현한 API 에 대해서 사장모드일때 /admin prefix 를 적용했습니다
- 테스트 코드 URL 도 수정했습니다
- 혹시 실수했는지도 몰라요 꼼꼼히 부탁드립니다 ! 
closes #229
> [BE] feat: 2차 구현기능 API 에 /admin prefix 를 적용한다(사장모드)

- backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
> [BE] fix: Coupon 엔티티 deleted 기본값 Boolean.TRUE 삭제

- backend/src/main/java/com/stampcrush/backend/api/cafe/CafeApiController.java
- backend/src/main/java/com/stampcrush/backend/api/cafe/request/CafeUpdateRequest.java
- backend/src/main/java/com/stampcrush/backend/application/cafe/CafeService.java
- backend/src/main/java/com/stampcrush/backend/application/cafe/dto/CafeUpdateDto.java
- backend/src/main/java/com/stampcrush/backend/entity/cafe/Cafe.java
- backend/src/test/java/com/stampcrush/backend/application/cafe/CafeServiceTest.java
- cafe controller, service에 기능 관련된 코드가 추가 됐습니다.
- update는 변경감지를 통해 진행했고, Cafe엔티티 안에 update메서드를 만들었습니다.
- update메서드에서 dto참조는 일부러 안했습니다! 도메인이 dto를 참조하는게 좋다고 생각하지 않기 때문입니다.
- 제가 구현한 API스펙의 introduction이 현재 Cafe엔티티에는 없습니다. 추가를 할까 하다가 테이블을 건드리는 일이라 정확한 진행상황을 모르는 제가 추가하기엔 애매하다고 판단되어 우선 introduction을 빼고 진행했습니다.
- 인수 테스트 역시 템플릿 등 인수 테스트를 어떻게 진행하기로 했는지 파악하지 못하고 있기 때문에, 생략했습니다. 이 부분은 파악하는대로 제가 코드 작성하겠습니다.
- openTime, closeTime관련 유효성 검증을 어떤 방식으로 하는게 좋을지 얘기해보면 좋을 것 같아요. 제가 생각한 유효성 검증이 필요한 것은 1. Null인지 2. hour(0~24), minute(0~60)의 범위 검증 3. closeTime이 openTime보다 늦는지. 이 정도가 있는 것 같아요. 이걸 커스텀 어노테이션으로 할 수도 있고, 생성자 안에서 할 수도 있을 것 같은데 어디서 하는게 괜찮다고 생각하시나요?
정해지는대로 코드 치겠습니다!
유효성 검증과, 인수 테스트를 제외하니 코드는 얼마 안되네요.. 배려해주셔서 감사합니다 ㅎㅎ
내일 일과시간에 리뷰 해주시면 예비군 끝나고 수정하기 위해서 미리 PR올리겠습니다! 
closes #231
> [BE] feat: 카페 정보 수정 API를 구현한다.

- backend/src/main/java/com/stampcrush/backend/BackendApplication.java
- backend/src/main/java/com/stampcrush/backend/config/PersistenceConfig.java
- SpringBootApplication 에 붙어있던 @EnableJpaAuditing 어노테이션을 따로 Configuration 클래스를 만들어서 분리했습니다
- [분리한 이유 참고 글](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.testing.spring-boot-applications.user-configuration-and-slicing)
- SpringBootApplication 이 테스트의 소스 구성이기 때문에 모든 슬라이스 테스트는 JpaAuditing 을 활성화하려고 시도합니다.         
- 그래서 @WebMvcTest 를 실행하면 Jpa 관련한 빈이 로드가 되지 않기 때문에 테스트가 실행이 되지 않습니다
- 결론
- 테스트 슬라이스는 @Configuration 클래스를 스캐닝하지 않기 때문에 원활한 슬라이스 테스트를 위해 @SpringBootApplication와 @EnableJpaAuditing를 분리했습니다
closes #260
> [BE] refactor: PersistenceConfig 추가하고 JpaAuditing 어노테이션 이동

- backend/src/main/java/com/stampcrush/backend/application/coupon/CouponService.java
- backend/src/main/java/com/stampcrush/backend/entity/cafe/CafePolicy.java
- backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
- backend/src/test/java/com/stampcrush/backend/application/coupon/CouponServiceTest.java
- backend/src/test/java/com/stampcrush/backend/entity/cafe/CafePolicyTest.java
- backend/src/test/java/com/stampcrush/backend/entity/coupon/CouponTest.java
- backend/src/test/java/com/stampcrush/backend/repository/coupon/CouponRepositoryTest.java
- CouponService의 createStamp메서드 로직을 while -> if문을 통한 분기로 코드 수정했습니다.
- 기존 쿠폰에 스탬프 찍혀있을 때 스탬프 적립하는 테스트 상황 추가했습니다.
- createStamp에서 고려한 상황은 아래와 같습니다.
1. 새롭게 찍은 스탬프 + 기존 스탬프 < 보상 스탬프 개수 
2. 새롭게 찍은 스탬프 + 기존 스탬프 == 보상 스탬프 개수 
3. 새롭게 찍은 스탬프 + 기존 스탬프 > 보상 스탬프 개수
이 순서대로 if문으로 분기 했습니다.
- Coupon, Customer등등을 조회하는 `repo.findById().orElseThrow`가 너무 많아지면서 가독성이 안좋아지더라구요. 그래서 createStamp에서는 orElseThrow만 있는 것도 별도의 private메서드로 분리했습니다!
- 전에 깃짱이 말한 CouponRepositoryTest의 `쿠폰들의_createdAt을_비교한다`를 repository에 작성한 이유가 생각이 났어요. createdAt은 repo를 통해 save될 때 생성이 되기 때문에 어쩔 수 없이 repositoryTest에 넣었던 기억이 있습니다.
closes #259
> [BE] refactor: 스탬프 발급 코드 리팩터링

- backend/src/main/java/com/stampcrush/backend/api/favorites/FavoritesController.java
- backend/src/main/java/com/stampcrush/backend/api/favorites/request/FavoritesUpdateRequest.java
- backend/src/main/java/com/stampcrush/backend/application/favorites/FavoritesService.java
- backend/src/main/java/com/stampcrush/backend/entity/favorites/Favorites.java
- backend/src/main/java/com/stampcrush/backend/repository/favorites/FavoritesRepository.java
- backend/src/test/java/com/stampcrush/backend/application/favorites/FavoritesServiceTest.java
카페 즐겨찾기 등록 및 해제 기능을 구현
현재, 카페 즐겨찾기를 등록할 때, `Favorites` 테이블에 이미 데이터가 존재한다면, `isFavorites` 필드만 수정해주고, 
처음 들어오는 데이터라면 새로 저장을 하는 로직을 짰습니다.
그래서 이 요청이 `Post`인지 `Patch`인지 헷갈리네요.
데이터베이스에 없다면 삽입을 하고 있다면 업데이트인데.. 여러분의 생각은 어떠신가요 ...??????
인수테스트와, 컨트롤러 단위테스트는 `base64`인증 과정이 들어오고 나서 한번에 짜겠습니다 !
**Header** 
- 데이터베이스 설계에 따라 변경될 수 있음.
```http
POST /api/cafes/{cafeId}/favorites
Authorization: username@password Base64 (customer)
```
**Body**
```json
{
"isFavorites": true || false
}
```
**Header**
- 데이터베이스에서 어떻게 사용할지에 따라서 변경될 수 있음.
```json
HTTP/1.1 200 OK
```
closes #258
> [BE] feat: 카페 즐겨찾기 등록 및 해제 기능을 구현한다.

- frontend/src/mocks/handlers.ts
- frontend/src/mocks/mockData.ts
- frontend/src/pages/CouponList/Coupon/index.tsx
- frontend/src/pages/CouponList/Coupon/style.tsx
- frontend/src/pages/CouponList/CouponDetail/index.tsx
- frontend/src/pages/CouponList/CouponDetail/style.tsx
- frontend/src/pages/CouponList/FlippedCoupon/index.tsx
- frontend/src/pages/CouponList/FlippedCoupon/style.tsx
- frontend/src/pages/CouponList/index.tsx
- frontend/src/pages/CouponList/style.tsx
- frontend/src/style/keyframes.ts
- frontend/src/types/index.ts
- 쿠폰 상세 페이지를 구현했습니다.
- 화면에 표시되는 쿠폰의 index와 `currentIndex`가 일치하지 않는 오류가 있어 수정하였습니다. 
- 월요일에 만나서 설명드릴테지만, 상세페이지가 열릴 때 실제 Y축 - 방향으로 이동하는 `Coupon` 컴포넌트와 상세 페이지에서 뒤집으며 확인하는 쿠폰은 다른 컴포넌트입니다.
++ 동작 화면에서는 확인할 수 없지만 쿠폰을 뒤집어 스탬프를 확인할 수 있음을 명시했습니다.
동작 화면
closes #207
> [FE] feat: 쿠폰 상세 모달 컴포넌트를 구현한다. 

- frontend/webpack.common.js
- frontend/webpack.dev.js
- webpack.common.js와 webpack.dev.js 두 파일의 중복되는 코드를 제거하고 dev로 이동시켰습니다. 해당부분이 현재 admin에서 오류가 나는데, api 추상화 코드에 admin prefix가 부재해서 그렇습니다. 즉시 이슈 발행하도록 하겠습니다.
closes #266
> [FE] refactor: webpack.common.js의 중복되는 코드를 dev로 이동

- frontend/src/Router.tsx
- frontend/src/components/Template/CustomerTemplate/index.tsx
- frontend/src/components/Template/CustomerTemplate/style.tsx
- frontend/src/pages/CouponList/CouponDetail/style.tsx
- frontend/src/pages/CouponList/style.tsx
- frontend/src/style/keyframes.ts
- 최소 태블릿(768px) 뷰포트 기준으로 pc환경에서의 뷰를 최대한 모바일에서 보이는 것처럼 변경했습니다.
동작 화면
closes
> [FE] refactor: 고객 모드의 화면을 PC환경에서도 모바일뷰로 렌더링한다. 

- frontend/src/components/ProgressBar/index.tsx
- frontend/src/pages/CouponList/index.tsx
- frontend/src/utils/index.ts
unsplash나 picksom과는 다르게 google drive의 이미지 url은 color-thief-react가 제대로 작동하지 않는 문제가 있었습니다. 
찾아보니까 cors에러였고, 구글 프록시 서버를 넣어줌으로써 해결하였습니다.🎊
[참고링크](https://lokeshdhakar.com/projects/color-thief/)
closes #280
> [FE] fix: 구글드라이브 호스팅 이미지 url color-thief cors에러 해결

- frontend/src/mocks/mockData.ts
- frontend/src/pages/Admin/ManageCafe/index.tsx
- frontend/src/pages/CouponList/CouponDetail/index.tsx
- frontend/src/pages/CouponList/FlippedCoupon/index.tsx
- frontend/src/pages/CouponList/index.tsx
- frontend/src/style/GlobalStyle.tsx
- api 명세와 다른 데이터 처리로 인한 오류 해결
- 스탬프를 stampCount만큼 그리지 않는 오류 해결
- 쿠폰 0개일 때의 화면이 렌더링되지 않는 오류 https://github.com/woowacourse-teams/2023-stamp-crush/issues/295 와 동일
- 현재 배포 중인 코드와 동일하게 수정
closes
> [FE] bug: 배포 중 발견한 오류를 해결한다.

- backend/src/main/java/com/stampcrush/backend/api/visitor/coupon/VisitorCouponFindApiController.java
- backend/src/main/java/com/stampcrush/backend/application/visitor/coupon/VisitorCouponFindService.java
- backend/src/main/java/com/stampcrush/backend/application/visitor/favorites/VisitorFavoritesFindService.java
- 구현 시점에 하디의 favorites 내용이 없어서, 하드코딩으로 박아놨었는데 추가되어서 이후에 저도 변경했습니다.
- repository는 하디가 작성했던 메서드를 그대로 사용했는데, 테스트 코드가 없더라고요. favorites의 동작과 운명을 같이하겠습니다. 
closes #309
> [BE] fix: 고객 쿠폰 조회에서 isFavorites를 상수가 아닌 데이터베이스 값으로 변경한다 

- frontend/src/pages/CouponList/CafeInfo/index.tsx
- frontend/src/pages/CouponList/CafeInfo/style.tsx
- frontend/src/pages/CouponList/Coupon/index.tsx
- frontend/src/pages/CouponList/CouponDetail/index.tsx
- frontend/src/pages/CouponList/CouponDetail/style.tsx
- frontend/src/pages/CouponList/FlippedCoupon/style.tsx
- frontend/src/pages/CouponList/index.tsx
- 쿠폰리스트 ->  마이페이지 -> 다시 쿠폰리스트에 왔을때, 컴포넌트가 재렌더링되어 useState의 currentIndex가 0이 되어서 쿠폰이 넘어가지 않던 버그를 refetch를 통해 해결하였습니다.
- 쿠폰리스트 파일의 코드가 너무 길어져서 상단 카페 정보 부분의 코드를 컴포넌트로 분리하였습니다.
closes
> [FE] fix: 3차데모 이후 발견한 버그 수정 및 리팩토링

- backend/src/main/java/com/stampcrush/backend/api/visitor/coupon/response/CustomerCouponFindResponse.java
- backend/src/main/java/com/stampcrush/backend/application/visitor/coupon/VisitorCouponFindService.java
- backend/src/main/java/com/stampcrush/backend/application/visitor/coupon/dto/CustomerCouponFindResultDto.java
- 라잇과 해당 API response 형태를 수정하기로 해서, 작게 수정했습니다! 
- 수정 후
```json
{
"coupons" : [ 
{
"cafeInfo": {
"id": 1,
"name": "하디카페",
"isFavorites": true,
},
"couponInfos": [ 
{
"id": 1,
"status": "ACCUMULATING" ("REWARDED", "EXPIRED"),
"stampCount" : 3,
"maxStampCount" : 8,
"rewardName": "아메리카노",
"frontImageUrl": "http://localhost:3000",
"backImageUrl" : "http://localhost:3000",
"stampImageUrl" : "http://localhost:3000",
"coordinates" : [
{
"order" : 1,
"xCoordinate" : 2,
"yCoordinate" : 5
},
{
"order" : 2,
"xCoordinate" : 5,
"yCoordinate" : 5
},
}
// ... 
],
},
// 카페 여러 개 
]
}
```
closes #371
> [BE] refactor: API 변경사항에 맞도록 CustomerCouponFindResponse 수정

- frontend/src/pages/Admin/ManageCafe/index.tsx
- frontend/src/pages/Admin/ManageCafe/style.tsx
- frontend/src/pages/CouponList/CouponDetail/index.tsx
- frontend/src/pages/CouponList/CouponDetail/style.tsx
- frontend/src/pages/CouponList/index.tsx
- frontend/src/utils/index.ts
ㄴ 해당 문제를 해결하기 위해 기존에 `CouponList.index.tsx`에 존재하던 `cafeId` 상태를 제거하였습니다. 
상태가 비동기적으로 동작하기 때문에 해당 문제가 발생하는 것으로 판단하였고, `CurrentCoupon`의 `cafeInfo.id`를 `CouponDetail` 컴포넌트에 `props`로 전달하여 최신 상태의 `cafeId`를 컴포넌트가 알게 하고자 하였습니다. 
`CouponDetail` 내부에서 `useQuery`로 `get` 요청을 보내고 `useEffect` 내에서 `refetch`를 하도록 하였는데, 다른 방법으로 `refetch`를 할 수 있는 방법을 알고 계신 리뷰어께서는 말씀해주시면 감사하겠습니다.
++ 유틸의 `parsePhoneNumber`을 닉값을 하기 위해 `정규표현식`으로 바꾸어봤습니다.
closes #358 
closes #360 
closes #370
> [FE] bug: 쿠폰 상세 페이지에서 발생한 버그를 수정한다. 

- backend/src/test/java/com/stampcrush/backend/acceptance/RewardAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/api/reward/ManagerRewardFindApiControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/reward/MangerRewardCommandApiControllerTest.java
- `ManagerRewardCommandApiController`, `ManagerRewardFindApiController` 단위 테스트 작성
- 리워드 사용과 조회 인수테스트 작성
- 컨트롤러 단위 테스트에서 인증 관련 `webConfig`는 필터로 제외하였습니다.
- 그 이유는 컨트롤러의 파라미터 바인딩, 예외 처리에 관련된 부분을 제외하고 추가적인 작업이라 생각이 들어서입니다.
- 인증관련된 테스트는 하나로 하는것도 괜찮아보입니다.
closes #337
> [BE] refactor: 리워드 조회와 사용에 관한 테스트 추가 작성

- frontend/src/api/delete.ts
- frontend/src/api/index.ts
- frontend/src/mocks/handlers.ts
- frontend/src/pages/CouponList/CouponDetail/index.tsx
- frontend/src/pages/CouponList/CouponDetail/style.tsx
- frontend/src/pages/CouponList/index.tsx
- 쿠폰 상세 페이지의 쿠폰 삭제 기능을 구현하였습니다.
- `Alert`를 사용하여 재차 확인합니다.
- 통신 없이 동작만을 구현하였습니다.
closes #395
> [FE] feat: 쿠폰 상세 페이지의 쿠폰 삭제 기능을 구현한다.

- backend/src/main/java/com/stampcrush/backend/api/manager/coupon/response/CafeCustomerFindResponse.java
- backend/src/main/java/com/stampcrush/backend/api/manager/coupon/response/CafeCustomersFindResponse.java
- backend/src/main/java/com/stampcrush/backend/api/manager/coupon/response/CustomerAccumulatingCouponFindResponse.java
- backend/src/test/java/com/stampcrush/backend/acceptance/coupon/ManagerCouponCommandIntegrationTest.java
- backend/src/test/java/com/stampcrush/backend/api/coupon/ManagerCouponCommandApiControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/coupon/ManagerCouponFindApiControllerTest.java
- 테스트 컨벤션에 맞춰 테스트 코드 수정했습니다.
- reponse의 localDateTime들은 String으로 넘겨주도록 수정했습니다.
- 프론트에서도 String으로 받더라구요
- 현재 응답dto의 LocalDateTime에 @JsonFormat이 붙어있는데 이로 인해 역직렬화 문제가 있어서 해결해야 합니다.
close #346
> [BE] refactor: 쿠폰 발급, 스탬프 적립, 쿠폰 적립하는 고객 조회에 대한 api테스트 작성

- backend/src/main/java/com/stampcrush/backend/application/manager/coupon/ManagerCouponCommandService.java
- backend/src/main/java/com/stampcrush/backend/entity/visithistory/VisitHistory.java
- backend/src/main/java/com/stampcrush/backend/repository/visithistory/VisitHistoryRepository.java
- backend/src/test/java/com/stampcrush/backend/application/coupon/ManageCouponCommandServiceTest.java
- stamp적립 서비스 로직에서 VisitHistoryRepository.save()만 추가했습니다~
closes #425
> [BE] feat: 스탬프 적립 시 VisitHistory데이터를 추가한다.

- backend/src/test/java/com/stampcrush/backend/acceptance/CafeCouponSettingIntegrationTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/CafeIntegrationTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/CustomerCouponFindAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCafeCouponSettingCommandUpdateAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCouponCommandAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCustomerCommandAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerRewardCommandAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerSampleCouponFindAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/VisitorCafeFindAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/VisitorCouponFindAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/VisitorFavoritesCommandAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerCafeCouponSettingUpdateStep.java
- backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerCafeCreateStep.java
- backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerCouponCreateStep.java
- backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerCouponFindStep.java
- backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerStampCreateStep.java
- backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerTemporaryCustomerCreateStep.java
- backend/src/test/java/com/stampcrush/backend/acceptance/step/VisitorCafeFindStep.java
- backend/src/test/java/com/stampcrush/backend/acceptance/step/VisitorCouponFindStep.java
- backend/src/test/java/com/stampcrush/backend/api/docs/DocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/fixture/CafeFixture.java
- backend/src/test/java/com/stampcrush/backend/fixture/CouponDesignFixture.java
- backend/src/test/java/com/stampcrush/backend/fixture/CouponPolicyFixture.java
- backend/src/test/java/com/stampcrush/backend/fixture/CustomerFixture.java
너무 변경 파일이 많아서 보기 까다로울 것 같아서 리팩터링한 부분 글로 작성했으니, 꼭 읽고 파일은 훑어보면 될 것 같습니당.
아래 내용 모두 한 건 아니고, step 클래스 이름 바뀐 것 때문에 새로 작성하는 코드에서 못 쓸 것 같아서, 일단 먼저 올려놓을게요! 
이후에 한 번 더 PR을 요청해야 할 것 같아요
- acceptance 패키지에 들어있던 테스트들 전부 AcceptanceTest로 만들고, 최대한 블랙박스 테스트로 만들었음.
- 블랙박스 테스트: RestAssured 들어간 요청 보내는 부분들을 최대한 분리해서 외부에서 우리 API의 상세 내용을 알 수 없도록 함.
- 따라서 분리할 수 있는 부분은 최대한 step으로 분리하고, 공통적인 부분들은 상수를 최대한 없애는 방향으로 리팩터링함.
- 중간에 인증 헤더 없이 보낸 경우에 대한 반환 같이 불가피한 경우를 제외하고 정상적인 동작만을 step 패키지 안으로 분리함.
- Fixture 역시 최대한 분리함.
- 특정 필드가 영속화된 내용이어야 하는 경우에는, 일단 public static 메서드로 해당 부분을 파라미터로 받도록 변경함.
- 테스트 효율성 향상
- 현재 Controller, Service slice test의 경우에 모든 코드가 다 각자 동일한 MockBean을 중복해서 생성하고 있음.
- 따라서 상위의 ControllerTest, ServiceTest를 생성하고, 공통적인 부분은 모두 분리함.
closes
> [BE] refactor: 테스트 코드의 step, Fixture 공통 부분 분리 및 테스트 효율성 향상

- backend/src/main/java/com/stampcrush/backend/api/visitor/coupon/VisitorCouponCommandApiController.java
- backend/src/main/java/com/stampcrush/backend/application/visitor/coupon/VisitorCouponCommandService.java
- backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
- backend/src/main/java/com/stampcrush/backend/exception/CouponNotFoundException.java
- backend/src/main/java/com/stampcrush/backend/repository/coupon/CouponRepository.java
- backend/src/test/java/com/stampcrush/backend/api/visitor/coupon/VisitorCouponCommandApiControllerTest.java
- backend/src/test/java/com/stampcrush/backend/application/visitor/coupon/VisitorCouponCommandServiceTest.java
- backend/src/test/java/com/stampcrush/backend/entity/coupon/CouponTest.java
- backend/src/test/java/com/stampcrush/backend/repository/coupon/CouponRepositoryTest.java
- 쿠폰 삭제 기능 구현
**Header**
```json
DELETE /api/coupons/{couponId}
**Authorization: username@password Base64 (customer**)
```
**Body**
None
**Header** 
```json
HTTP/1.1 204 NO CONTENT
```
**Body**
None
- `Step`클래스가 완료되면 인수테스트 넣겠습니다.
- 쿠폰 삭제시 이미 쿠폰이 삭제되있는 경우를 따로 체크하지 않았습니다. 체크하지 않았기에 예외를 따로 던지지도 않고요. 
만약 이미 삭제된 쿠폰에 대해 삭제하라는 요청이 다시 왔을 경우 예외를 터트려야하는가에 대해서 저는 예외를 던지지 않아도 된다는 입장입니다. 결국 클라이언트가 원한 결과는 `쿠폰이 삭제가 된다` 입니다. 그렇기에 쿠폰이 이미 삭제가 된 상태라고 해도 이 경우는 요청이 기대하는 바와 일치하기 때문에 따로 예외를 던지지 않아도 된다고 생각합니다.
여러분의 의견은 어떤지 여쭤보고 싶습니다 !
closes #438
> [BE] feat: 쿠폰 삭제 기능을 구현한다

- backend/src/main/java/com/stampcrush/backend/application/manager/coupon/ManagerCouponFindService.java
- backend/src/main/java/com/stampcrush/backend/repository/reward/RewardRepository.java
- backend/src/test/java/com/stampcrush/backend/application/manager/coupon/ManagerCouponFindServiceTest.java
- backend/src/test/java/com/stampcrush/backend/repository/reward/RewardRepositoryTest.java
사장님이 고객의 남은 리워드 개수를 조회할 때, 이미 사용한 리워드까지 조회되는 문제를 해결했습니다.
바뀐 부분이 많지는 않습니다.
`RewardRepository`에 대한 의존성 추가를 했습니다.
찾아보니 SpringDataJpa에서 `count` 쿼리의 반환 타입이 `Long`이더군요.
그래서 int로 강제 캐스팅을 했는데, DTO의 rewardcount field type을 Long으로 바꿔도 될것같습니다.
여러분의 의견은 ?? 저는 후자긴해요..(함부로 바꾸면 안될것같아 전자의 방법으로 일단 구현해놨습니다.)
closes #380
> [BE] refactor: 남은 리워드 개수 구하는 로직 수정

- backend/src/main/resources/logback-spring.xml
- warn.log에 warning로그 찍히도록 logback-spring.xml수정했습니다.
- 지금 spring에서 찍는 로그 + 우리가 찍는 로그가 다 log파일에 찍히는데 우리가 찍는 로그만 기록할지 말지 얘기해보고 적용하면 될 거 같아요.
- profile별로 로그 전략 다르게 가져갈 수 있는데 일단 급한게 warn로그 안찍히는거라 이 부분은 아직 안했습니다.
closes
> [BE] fix: warning 로그 찍히도록 수정

- backend/src/main/java/com/stampcrush/backend/application/manager/coupon/ManagerCouponFindService.java
- backend/src/main/java/com/stampcrush/backend/entity/visithistory/VisitHistories.java
- 카페에 스탬프가 없는 쿠폰을 가지고 있는 고객이 존재하면 사장이 고객 목록을 조회해올때 에러가 발생합니다
- 임시 고객일때 스탬프가 없는 쿠폰을 가지게 되는 경우가 생깁니다
- 스탬프가 찍힐때 방문 이력 테이블에 이력이 찍히게 되기 때문에 방문 이력 테이블에서 카페와 고객을 기준으로 조회해왔을때 빈 배열이 반환될때 에러가 나게해놨는데 에러 발생하는거 제거해놨습니다 (임시방편)
- 현재는 스탬프가 없는 쿠폰을 가지고 있는 고객은 방문횟수가 0번, 첫 방문일이 현재 시간으로 반환되게끔 수정했습니다
closes
> [BE] fix: 스탬프가 없는 쿠폰을 가지고 있는 고객이 존재하면 방문이력 에러 발생 없앰 (임시 방편)

- backend/src/main/java/com/stampcrush/backend/application/visitor/coupon/VisitorCouponFindService.java
- backend/src/main/java/com/stampcrush/backend/repository/coupon/CouponRepository.java
- backend/src/test/java/com/stampcrush/backend/application/visitor/coupon/VisitorCouponFindServiceTest.java
- backend/src/test/java/com/stampcrush/backend/repository/coupon/CouponRepositoryTest2.java
- 프론트에서 현재 정렬 로직이 없어서 백엔드에서 정렬해서 보내주겠습니다 
- 즐겨찾기 해제된게 앞으로 오도록 정렬해달라고 해서 그렇게 했습니당
closes #570
> [BE] feat: Coupon 즐겨찾기에 따라 정렬

- backend/src/main/java/com/stampcrush/backend/api/manager/cafe/ManagerCafeCouponSettingFindApiController.java
- backend/src/main/java/com/stampcrush/backend/application/manager/cafe/ManagerCafeCouponSettingFindService.java
- backend/src/main/java/com/stampcrush/backend/application/manager/cafe/dto/CafeCouponSettingFindResultDto.java
- backend/src/test/java/com/stampcrush/backend/api/manager/cafe/ManagerCafeCouponSettingFindApiControllerTest.java
- backend/src/test/java/com/stampcrush/backend/application/manager/cafe/ManagerCafeCouponSettingFindServiceTest.java
- 기존 CafeCoupon조회였는데, Coupon조회 후 Coupon의 CouponDesign에서 이미지 조회하도록 수정했습니다.
closes #567
> [BE] feat: 사장이 고객의 쿠폰 조회 시 쿠폰 발급 당시 이미지 조회

- frontend/src/api/get.ts
- frontend/src/pages/Admin/EarnStamp/SelectCoupon/index.tsx
- 사용자가 가진 쿠폰의 정책에 부합하는 이미지를 불러온다.
closes #577
> [FE] feat: 변경된 api에 대응한다

- backend/build.gradle
- backend/src/main/java/com/stampcrush/backend/api/manager/cafe/ManagerCafeCouponSettingFindApiController.java
- backend/src/main/java/com/stampcrush/backend/api/visitor/profile/VisitorProfilesCommandApiController.java
- backend/src/test/java/com/stampcrush/backend/api/docs/DocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/auth/ManagerOAuthApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/manager/cafe/ManagerCafeCouponSettingFindApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/manager/image/ManagerImageCommandApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/visitor/profile/VisitorProfilesCommandApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/visitor/profile/VisitorProfilesFindApiDocsControllerTest.java
- 고객 모드 프로필 조회
- 고객 모드 핸드폰 번호 등록
- 현재 카페의 카페 쿠폰 디자인 세팅 정보 불러오는 API
- 사장이 고객의 쿠폰 조회시 쿠폰 발급 당시 이미지 조회
- 이미지 업로드
- 회원가입 (이건 AuthController Test profile 분리해야 해서 disable)
closes #526
> [BE] feat: 4차 데모데이때 추가된 API 에 대한 문서화 테스트를 작성한다 

- frontend/src/components/Modal/style.tsx
- frontend/src/pages/CouponList/FlippedCoupon/style.tsx
- 해당 문제는 `top`, `left`가 고정된 스탬프와 너비가 `vw`단위인 모달 `width`의 상대, 절대적 좌표 문제임을 인식하였습니다.
- 해당 문제를 해결하기 위해 `width`를 `fit-content`로 변경하여 해당 문제를 해결하였습니다.
- 또한 위 문제와 같이 제기되었던 FlippedCoupon에서의 스탬프 이미지 사이즈를 비율에 맞게 조정하여 사용자가 기대하는 쿠폰의 모습을 띄도록 하였습니다.
1. 윈도우 리사이즈 이후에도 스탬프의 위치가 변경되지 않는 모습
<br/>
<br/>
2. 비율에 맞게 스탬프의 사이즈를 조정함으로써 사용자가 기대하는 쿠폰의 모습을 보여줌
closes #566
> [FE] 커스텀 스탬프 창의 사이즈가 변할 때 쿠폰 위에 따라다니지 않는 문제를 해결한다.

- backend/src/main/java/com/stampcrush/backend/api/visitor/profile/VisitorProfilesFindApiController.java
- backend/src/main/java/com/stampcrush/backend/api/visitor/profile/response/VisitorProfilesFindByPhoneNumberResponse.java
- backend/src/main/java/com/stampcrush/backend/application/visitor/profile/VisitorProfilesCommandService.java
- backend/src/main/java/com/stampcrush/backend/application/visitor/profile/VisitorProfilesFindService.java
- backend/src/main/java/com/stampcrush/backend/application/visitor/profile/dto/VisitorProfileFindByPhoneNumberResultDto.java
- backend/src/test/java/com/stampcrush/backend/api/visitor/profile/VisitorProfilesFindApiControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/visitor/profile/response/VisitorProfilesFindByPhoneNumberResponseTest.java
- backend/src/test/java/com/stampcrush/backend/application/visitor/profile/VisitorProfilesCommandServiceTest2.java
- backend/src/test/java/com/stampcrush/backend/application/visitor/profile/VisitorProfilesFindServiceTest.java
- 임시 회원 데이터 연동 과정에서 필요한 API임.
- 왜 필요한지는 [디스커션](https://github.com/woowacourse-teams/2023-stamp-crush/discussions/619)에 써놨으니 꼭 꼭 꼭 확인.. 너무 힘드니 묻지 말아주세요....
- 데이터 연동 API를 만들다가 어제 큰 수정이 필요하다고 논의했고, 수정 전에 이 API는 먼저 머지하는게 좋을 것 같아서 PR 올렸습니다. 
```http
GET /api/customers/profiles/serach?phone-number=01038626099 HTTP/1.1
Authorization: Bearer k21h3keeoiu3k2lkl12j3kdksuhxcb_120909
```
**Body**
None
**Header**
```http
HTTP/1.1 200 OK
```
**Body**
- 해당 전화번호의 임시 회원(Temporary Customer)이 존재하는 경우 => 프론트에서 연동할거냐고 물어볼 예정
```json
{
"customers": [
{
"id": 300,
"nickname": "6099",
"phoneNumber": "01038626099",
"registerType": "temporary"
}
]
}
```
- 해당 전화번호의 가입 회원(Register Customer)이 존재하는 경우 => 프론트에서 이경우에는 일단 해당 번호로 저장을 못하게 할 예정
```json
{
"customers": [
{
"id": 300,
"nickname": "6099",
"phoneNumber": …
```
> [BE] feat: 고객모드의 전화번호로 고객 조회 API

- backend/src/main/java/com/stampcrush/backend/api/visitor/profile/VisitorProfilesCommandApiController.java
- backend/src/main/java/com/stampcrush/backend/api/visitor/profile/VisitorProfilesLinkDataDto.java
- backend/src/main/java/com/stampcrush/backend/api/visitor/profile/VisitorProfilesLinkDataRequest.java
- backend/src/main/java/com/stampcrush/backend/application/visitor/profile/VisitorProfilesCommandService.java
- backend/src/main/java/com/stampcrush/backend/auth/api/VisitorAuthController.java
- backend/src/main/java/com/stampcrush/backend/auth/application/VisitorAuthService.java
- backend/src/main/java/com/stampcrush/backend/auth/request/OAuthRegisterCustomerCreateRequest.java
- backend/src/main/java/com/stampcrush/backend/entity/user/Customer.java
- backend/src/test/java/com/stampcrush/backend/acceptance/VisitorLinkDataAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/step/VisitorJoinStep.java
- backend/src/test/java/com/stampcrush/backend/acceptance/step/VisitorLinkDataStep.java
- backend/src/test/java/com/stampcrush/backend/api/visitor/profile/VisitorProfilesCommandApiControllerTest.java
- 회원 데이터 연동 API 작성했습니다.
- 테스트 용도로 임시 회원가입 API도 생성했습니다. 
구체적인 플로우가 약간 어려우면, 제가 [엄청 자세히 적어놓은 블로그 글](https://engineerinsight.tistory.com/193#%E2%9C%94%20API%20%EB%AA%85%EC%84%B8-1) 있으니 참고해주세요! 
- request dto에서 연동할 register customer id를 받음.
- JPA 자동 변경 감지 통해서 temporary customer의 nickname, ... oauth 관련 칼럼, customer type 변경함.
- 현재 로그인되어 있는 register customer 회원 삭제해버림.
- 로컬에서는 로그인하고 access token 받는게 아직 안돼서 아직 테스트를 못해봤는데, 현재 로그인되어 있는 회원을 삭제해 버리니깐, 연동 이후에 바로 로그아웃 당할 것 같아요. 다시 로그인하면 그때부터는 연동된 customer를 찾게 될 것 같아요.
- 이거 안된다면 조금 회의가 필요함...! 
- 서비스 코드에서 뭐하는지 최대한 명확하게 하려고 메서드 분리 일부러 안했어요! 
closes #623
> [BE] feat: 회원 데이터 연동 API 

- frontend/src/pages/Customer/CouponList/index.tsx
- frontend/src/types/index.ts
- frontend/src/utils/index.ts
- 쿠폰이 한 장일 때 애니메이션을 동작하지 않게 하였습니다.
- 해당 부분 수정 중 발견한 오류를 해결하였습니다
- 쿠폰이 한 장일 때 삭제 -> 사장모드에서 스탬프 적립 -> 렌더링 되지 않는 오류 발생
- 원인 : `currentIndex`가 -1이 되어 발생하는 오류
- 해결 : `useEffect` 내부 로직 중 `couponData`가 비어있어도 `setCurrentIndex`가 동작하였음. 조건을 추가하여 방지하였습니다.
closes #632
> [FE] refactor: 쿠폰이 한 장일 때 쿠폰을 넘기는 애니메이션이 동작하지 않게 한다. 

- backend/src/main/java/com/stampcrush/backend/application/visitor/profile/dto/VisitorProfileFindByPhoneNumberResultDto.java
- backend/src/main/java/com/stampcrush/backend/entity/user/Customer.java
- backend/src/main/java/com/stampcrush/backend/entity/user/CustomerType.java
- backend/src/test/java/com/stampcrush/backend/api/visitor/profile/VisitorProfilesFindApiControllerTest.java
younho cha가 정신이 없었는지..
프론트에 보내는 메세지를 거꾸로 지정해 놨더라고요
수정했습니다. 
closes
> [BE] fix: CustomerType에서 이름을 거꾸로 지정한 문제 해결 

- frontend/src/api/post.ts
- #653 
이슈 이름과 동일합니다.
closes #653
> [FE] fix: 이미지 업로드 요청 인증 헤더 추가

- backend/src/main/java/com/stampcrush/backend/application/manager/reward/ManagerRewardFindService.java
- backend/src/main/java/com/stampcrush/backend/repository/visithistory/VisitHistoryRepository.java
- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerRewardFindAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/application/manager/reward/ManagerRewardCommandServiceTest.java
- backend/src/test/java/com/stampcrush/backend/repository/visithistory/VisitHistoryRepositoryTest.java
- 풀리퀘 #678 과 동일한 변경입니다
- 깃꼬여서 다시 PR 올렸습니다
- 어프루브 다 받은거 + 제가 맡은 부분 인수테스트 회원가입 API 로 수정하려면 이 PR 이 머지가 되어야 해서 머지하겠습니다
closes #523
> [BE] feat: 자신의 카페 고객이 아니면 리워드 조회 불가능하게 수정

- backend/src/test/java/com/stampcrush/backend/api/docs/manager/cafe/ManagerCafeCommandApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/manager/cafe/ManagerCafeCouponSettingCommandApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/manager/cafe/ManagerCafeCouponSettingFindApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/manager/cafe/ManagerCafeFindApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/manager/coupon/ManagerCouponCommandApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/manager/coupon/ManagerCouponFindApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/manager/customer/ManagerCustomerCommandApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/manager/customer/ManagerCustomerFindApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/manager/image/ManagerImageCommandApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/manager/reward/ManagerRewardCommandApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/manager/reward/ManagerRewardFindApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/manager/sample/ManagerSampleCouponFindApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/visitor/cafe/VisitorCafeFindApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/visitor/coupon/VisitorCouponCommandApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/visitor/coupon/VisitorCouponFindApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/visitor/favorites/VisitorFavoritesCommandApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/visitor/profile/VisitorProfilesCommandApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/visitor/profile/VisitorProfilesFindApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/visitor/reward/VisitorRewardsFindApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/docs/visitor/visithistory/VisitorVisitHistoryFindApiDocsControllerTest.java
- 전화번호로 고객 조회, 임시 회원<-> 가입회원 연동에 대한 API 문서를 작성했습니다
- 인증방식 변경에 따른 테스트 문서 설명을 Basic -> Bearer 로 변경했습니다
closes #681
> [BE] feat: 5차 데모데이때 추가된 API 에 대한 문서화 테스트를 작성한다

- frontend/src/api/index.ts
현재 JWT access token이 만료된 상태에서 웹에 접근하면, 오류 페이지로 이동합니다. 지금까지 해결방법은 localStorage를 직접 비워주는 것밖에 방법이 없었습니다. 
현재 가지고 있는 토큰으로 인증을 시도하는데 만료된 토큰이라면 백엔드에서 401 HTTP 상태 코드가 반환됩니다. 따라서 최상단의 api 요청 로직에서 401 code일 시 토큰을 비워줍니다.
- 에러 처리하는 부분을 보면, 어떤 api 요청이든 customer, admin을 비워줄 수 밖에 없습니다. 이를 구분하려면 고객 요청과 사장님 페이지 요청을 각각 구분하여 사용하여야 될 것 같습니다. (TODO 에 남겨두었습니다.)
- 401보다 구체적인 에러코드가 나오면, 상태코드 대신 에러응답값을 이용해 에러핸들링을 해줘도 좋을 것 같습니다.
- 추가로 refresh token이 구현된 이후에서도 이 분기문 안에서 처리해줘도 좋을 것 같아요.
- #684 
closes #684
> [FE] fix: token 만료 시 만료된 토큰을 삭제한다.

- frontend/src/pages/Admin/CustomerList/hooks/useGetCustomers.ts
- frontend/src/pages/Admin/CustomerList/index.tsx
해당 [pr](https://github.com/woowacourse-teams/2023-stamp-crush/pull/695)을 머지한 후 빌드하다가 발생한 에러를 수정하였습니다.
에러가 발생한 이유는 다음과 같습니다. 
4번의 타입 단언을 피하고자 아래와 같이 리팩토링 하였었는데, 
훅을 사용하는 컴포넌트 단에서 타입에러가 발생했었습니다.
따라서 훅의 인자에 타입단언을 해주어서 해결하였습니다.
훅의 인자에 타입단언을 피하려면 SelectBox의 Option의 key 타입을 제네릭으로 받도록 추상화하여야 하는데, 
현재 SelectBox가 많은 페이지에서 사용되고 있기 때문에, 조금 더 고민해봐야할 것 같습니다.!!
closes #720
> [FE] fix: CustomerOrderOption 버그 수정

- frontend/src/pages/Customer/CouponList/CouponDetail/index.tsx
- frontend/src/pages/Customer/CouponList/CouponDetail/style.tsx
- `z-index`로 탭바를 가려서 보이지 않도록 했는데, 완벽한 대처는 아닌 것으로 생각합니다. 다른 방안이 있다면 피드백주세요.
- 주소가 화면 밖으로 삐져나오는 경우를 대처했습니다.
- 주소가 긴 경우 아이콘의 레이아웃이 망가지는데 해당 경우에 대한 대처로 `min-width`, `min-height`를 주어 해결했습니다.
closes #707
> [FE] bug: 고객모드의 카페 상세페이지에서 탭바를 보이지 않도록 한다. 

- backend/src/main/java/com/stampcrush/backend/application/manager/coupon/ManagerCouponFindService.java
- backend/src/main/java/com/stampcrush/backend/application/manager/reward/ManagerRewardFindService.java
- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerRewardFindAcceptanceTest.java
- 사장님의 고객목록 조회 시 방문횟수 0이면 반환값에서 제외
- 사장님의 리워드 사용 조회 시 전화번호로 조회된 고객이 카페의 고객이 아니면 NotFound 에러로 수정(현재 UnAuthorized 에러 발생 시 로그인 페이지로 리다이렉트 됨)
closes
> [BE] fix: 고객이 쿠폰만 있고 방문횟수가 없을때 에러 수정

- backend/src/main/java/com/stampcrush/backend/application/manager/customer/ManagerCustomerCommandService.java
- backend/src/main/java/com/stampcrush/backend/application/visitor/coupon/VisitorCouponFindService.java
- backend/src/main/java/com/stampcrush/backend/auth/api/VisitorAuthController.java
- backend/src/main/java/com/stampcrush/backend/auth/application/VisitorAuthService.java
- backend/src/main/java/com/stampcrush/backend/repository/coupon/CouponRepository.java
- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCustomerCommandAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCustomerFindAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerSampleCouponFindAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/VisitorCouponCommandAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/VisitorCouponFindAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerCafeCouponSettingUpdateStep.java
- backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerCafeCreateStep.java
- backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerCouponCreateStep.java
- backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerCustomerFindStep.java
- backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerJoinStep.java
- backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerSampleCouponFindStep.java
- backend/src/test/java/com/stampcrush/backend/acceptance/step/VisitorCouponDeleteStep.java
- backend/src/test/java/com/stampcrush/backend/acceptance/step/VisitorJoinStep.java
- backend/src/test/java/com/stampcrush/backend/application/visitor/coupon/VisitorCouponFindServiceTest.java
- backend/src/test/java/com/stampcrush/backend/repository/coupon/CouponRepositoryTest2.java
- 인수테스트에서 회원가입 로직 새로 만든 회원가입 API로 대체하기
- `Manager.customer` , `Manager.sample`, `Visitor.coupon`
closes
> [BE] test: Manager.customer , Manager.sample, Visitor.coupon 인수테스트 리팩터링

- frontend/src/components/Input/index.tsx
- 지난 금요일 발견한 오류에 대해 `main` 브랜치에 핫픽스했던 부분이 `develop` 브랜치와 달라 이후 충돌이 있을 것으로 예상됩니다. 따라서 두 브랜치 간 싱크를 맞추기 위해 해당 커밋을 `develop`에 머지 요청합니다.
closes #759
> [FE] refactor: 핫픽스한 `Input`의 싱크를 맞춘다

- backend/build.gradle
- backend/src/main/java/com/stampcrush/backend/application/manager/coupon/ManagerCouponCommandService.java
- backend/src/main/java/com/stampcrush/backend/application/manager/event/StampAccumulatingEventHandler.java
- backend/src/main/java/com/stampcrush/backend/application/manager/event/StampCreateEvent.java
- backend/src/main/java/com/stampcrush/backend/config/PersistenceConfig.java
- backend/src/main/java/com/stampcrush/backend/config/RequestLoggingFilter.java
- backend/src/main/resources/application-test.yml
- backend/src/test/java/com/stampcrush/backend/application/manager/coupon/ManageCouponCommandServiceTest.java
- stamp 적립 service 로직에서 stamp적립 이벤트를 발생시켰습니다.
- 로직 초반부에 위치 시켰는데 모든 로직이 끝나고 발생시키기 어려웠던 이유가 분기문 때문인데요 112, 116 로직에서 바로 return 을 하고 있습니다. (코드에 코멘트 달아놨습니다)
- 그래서 TransactionalEvenentListner를 활용해 스탬프 적립 트랜잭션이 commit 된 시점에 슬랙으로 메시지를 보내도록 했습니다.
- 해당 어노테이션의 기본 옵션이 기존 트랜잭션이 커밋되는 시점에 메서드 로직을 수행하는 옵션입니다 
- 시간이 부족해서 슬랙으로 메시지 보내는 기능만 구현했습니다. 메시지 보내는 부분 추상화, 이벤트 유실 까진 아직 구현을 못했네요..
closes #751
> [BE] feat: 스탬프 적립 시 슬랙으로 알림을 보낸다

- backend/src/main/java/com/stampcrush/backend/api/manager/coupon/ManagerCouponFindApiController.java
- backend/src/main/java/com/stampcrush/backend/api/manager/coupon/response/CafeCustomerFindResponse.java
- backend/src/main/java/com/stampcrush/backend/application/manager/coupon/CustomerCouponStatistics.java
- backend/src/main/java/com/stampcrush/backend/application/manager/coupon/ManagerCouponFindService.java
- backend/src/main/java/com/stampcrush/backend/application/manager/coupon/dto/CafeCustomerFindResultDto.java
- backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
- backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupons.java
- backend/src/main/java/com/stampcrush/backend/entity/user/CustomerType.java
- backend/src/main/java/com/stampcrush/backend/entity/visithistory/VisitHistories.java
- backend/src/main/java/com/stampcrush/backend/repository/coupon/CouponRepository.java
- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCouponCommandAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCouponFindAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerCustomerFindStep.java
- backend/src/test/java/com/stampcrush/backend/api/docs/manager/coupon/ManagerCouponFindApiDocsControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/manager/coupon/ManagerCouponFindApiControllerTest.java
- backend/src/test/java/com/stampcrush/backend/application/manager/coupon/ManagerCouponFindServiceTest.java
- backend/src/test/java/com/stampcrush/backend/entity/visithistory/VisitHistoriesTest.java
- backend/src/test/java/com/stampcrush/backend/fixture/CouponPolicyFixture.java
- backend/src/test/java/com/stampcrush/backend/repository/coupon/CouponRepositoryTest.java
- backend/src/test/java/com/stampcrush/backend/repository/coupon/CouponRepositoryTest2.java
- 기존 사장님이 고객목록 조회 api에 최근 방문일자 데이터도 추가했습니다.
- 임시회원, 가입회원을 조회할 수 있는 api 작성했습니다.
- 코드 조금 수정하니까 이전보다는 깔끔해진 것 같아서 CustomerStatistics 는 아직 안없앴습니다. 
closes #767
> [BE] feat: 임시회원, 가입회원 조회 api 구현 + 고객 목록 조회 시 최근 방문 일자 데이터 추가

- frontend/src/api/get.ts
- frontend/src/components/Header/SubHeader/style.tsx
- frontend/src/constants/index.ts
- frontend/src/pages/Admin/CustomerList/Customers/index.tsx
- frontend/src/pages/Admin/CustomerList/hooks/useGetCustomers.ts
- frontend/src/pages/Admin/CustomerList/index.tsx
- frontend/src/pages/Admin/CustomerList/style.tsx
- frontend/src/types/api/request.ts
- frontend/src/types/domain/customer.ts
- frontend/src/utils/index.ts
- 임시/회원 탭으로 구분
- 최근방문순 정렬 기능
closes #783
> [FE] feat: 임시, 회원 구분 및 최근방문순 추가

- frontend/src/pages/Admin/CouponDesign/ChoiceTemplate/style.tsx
- frontend/src/pages/Admin/CouponDesign/CouponPreviewSection/index.tsx
- frontend/src/pages/Admin/CouponDesign/CustomCouponDesign/index.tsx
- frontend/src/pages/Admin/CouponDesign/CustomCouponDesign/style.tsx
- frontend/src/pages/Admin/CouponDesign/CustomCouponSection/index.tsx
- frontend/src/pages/Admin/CouponDesign/CustomCouponSection/style.tsx
- frontend/src/pages/Admin/CouponDesign/CustomStampSection/index.tsx
- frontend/src/pages/Admin/CouponDesign/TemplateCouponDesign/index.tsx
- frontend/src/pages/Admin/CouponDesign/TemplateCouponDesign/style.tsx
- frontend/src/pages/Customer/CouponList/components/Coupon/style.tsx
쿠폰 미리보기는 img 태그이므로 `object-fit: cover`속성으로 이미지 비율을 맞추고
쿠폰 리스트의 이미지는 button 태그이므로 `background-size: cover`속성으로 이미지 비율을 맞추고 있었습니다.
둘 다 원본비율을 망가뜨리지 않으면서 이미지를 꽉채우기 위해 남는 부분을 "자르는데"
전자는 위 아래를 같이 자르고, 후자는 아래만 잘라서 이미지가 다르게 보였습니다.
후자에 `background-position: center`속성을 추가하여 문제를 해결하였습니다.
[ 해결된 상황 캡쳐 사진 ]
전
후
전
후
이 또한 서비스 런칭 초반 부에 보여지는 내용이므로 빠르게 머지되면 좋을 듯 합니다!
closes #724
> [FE] fix: 이미지 비율이 다른 문제 수정과 쿠폰 제작및 변경 ui 개선 

- frontend/src/hooks/useCustomerRedirectRegisterPage.ts
- frontend/src/pages/Customer/CouponList/index.tsx
- frontend/src/pages/Customer/HistoryPage/RewardHistory/index.tsx
- frontend/src/pages/Customer/HistoryPage/StampHistory/index.tsx
- frontend/src/pages/Customer/MyPage/index.tsx
- frontend/src/pages/Customer/RewardList/index.tsx
- 리다이렉션하는 훅을 생성하였습니다. 
- 다른 훅들과 다르게 return하는 값을 잘 쓰지 않아서 컴포넌트가 마운트됐을때 곧장 실행되도록했는데, 훅을 이런 식으로 사용한 적이 없다보니 어색하더라구요. 그렇다고 매번 검증하기 위해 보일러 플레이트를 작성하는 것도 낭비라는 생각이 들어 현재의 형태
```ts
useCustomerRedirectRegisterPage();
```
가 되었는데, 너무너무 어색합니다..
이 훅을 어떻게 해야 좀 자연스럽게 사용할 수 있을까요?
closes #803
> [FE] feat: 고객모드에서도 사장모드처럼 전화번호 미등록시 사용하지 못하게 한다.

- frontend/src/components/Template/style.tsx
- frontend/src/pages/Admin/EarnStamp/components/CouponIndicator.tsx
- frontend/src/pages/Admin/EarnStamp/index.tsx
- frontend/src/pages/Admin/EarnStamp/style.tsx
- frontend/src/pages/Admin/ManageCafe/components/PreviewContent/index.tsx
- frontend/src/pages/Admin/ManageCafe/components/PreviewContent/style.tsx
- frontend/src/pages/Admin/ManageCafe/components/PreviewCoupon/style.tsx
- frontend/src/pages/Admin/ManageCafe/index.tsx
- frontend/src/pages/Admin/ManageCafe/style.tsx
- 카페 관리의 미리보기 콘텐츠가 실제 고객모드와 상이하여 해당 부분 동일하게 표시되도록 변경했습니다.
- 적립 페이지를 가장 많이 사용하게 될텐데 사용 빈도에 비해 완성도가 부실해보여서 레이아웃과 UX를 개선했습니다.
- stepper와 쿠폰 간 여백을 줄였습니다.
- 사용자가 적립할 때 가장 필요한 정보는 스탬프 개수(숫자)라고 생각하여 폰트 컬러를 눈에 띄도록 변경했습니다.
- 현재 보유 스탬프 + 적립할 스탬프의 개수가 MaxCount보다 커지는 순간, 사용자에게 초과되는 스탬프는 새 쿠폰에 적립된다는 점을 고지하도록 했습니다.
- Template에 `overflow:scroll` 속성을 추가하였습니다.
-  이외에도 여러분이 생각하는 개선사항을 리뷰에 남겨주세요
before　　　　　　　　　　　　　　　　after
적립 페이지 UI/UX 개선
closes #802
> [FE] refactor: 카페 관리 페이지 내부의 미리보기 UI가 실제와 다른 부분 수정

- frontend/src/constants/index.ts
- frontend/src/pages/Admin/CustomerList/index.tsx
#814 깃짱의 제안을 반영하여, '전체'를 고객 필터링의 기본값으로 변경하였습니다.
저 또한 스탬프 적립 완료 후에 이동되는 고객리스트 페이지에서 즉시 새로 생성된 고객을 확인하려면 '회원'이 아닌 '전체' 탭이 먼저 보여야 한다고 생각이 들어 수정하였습니다~
closes #814
> [FE] feat: '전체'를 기본값으로 변경

- frontend/src/pages/Admin/CouponDesign/CustomCouponDesign/StampCustomModal/index.tsx
- frontend/src/pages/Admin/CouponDesign/CustomCouponDesign/StampCustomModal/style.tsx
- frontend/src/pages/Admin/CouponDesign/CustomCouponDesign/style.tsx
- frontend/src/pages/Customer/CouponList/components/FlippedCoupon/style.tsx
스탬프 이미지는 비율이 다르더라도 찌그러뜨리면 안되기 때문에 contain으로 수정하였습니다. 
closes #832
> [FE] fix: 스탬프 이미지 object-fit: contain 수정

- backend/src/main/java/com/stampcrush/backend/api/manager/coupon/request/StampCreateRequest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCouponCommandAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/VisitorRewardFindAcceptanceTest.java
- 스탬프 적립요청 최대 개수 10개로 했습니다
- max 적립 개수는 변경이 잦을 거 같아서 Request 에서만 @Max 로 막았습니다
closes
> [BE] hotfix: stamp 최대 적립 개수 10개로 고정

- frontend/package.json
- frontend/webpack.prod.js
새로운 버전 릴리즈 후에도 A2HS 적용이 되지 않는 걸 확인했습니다 😇
빌드된 dist 폴더를 확인하니 public 폴더에 넣어준, 앱로고파일과 manifest 설정 파일이 없더라구요 😇
dev환경에서는 아래처럼 public내용을 함께 빌드해주고 있어서 로컬에서 테스트할때는 A2HS 적용을 확인할 수 있었던 것이었어요 😇
```javascript
devServer: {
static: {
directory: path.join(__dirname, 'public'),
},
historyApiFallback: true,
port: 3000,
hot: true,
},
```
[copy-webpack-plugin](https://webpack.js.org/plugins/copy-webpack-plugin/)을 webpack.prod.js에 추가해주어 해결하였습니다. 
빌드 폴더 전과 후
<p align="center">
</p>
[참고자료](https://pak-fuse.tistory.com/48)
끝나지 않는 A2HS 관련 pr이네요.. 😓 송구스럽습니다~
closes #849
> [FE] fix: 배포환경에서 manifest 파일이 포함되지 않는 문제 수정

- frontend/src/pages/Admin/CustomerList/index.tsx
- frontend/src/pages/Admin/CustomerList/style.tsx
사장모드에서 고객이 현재 몇명인지 확인하기 어려운 불편함이 있었습니다.
따라서, 고객의 수를 ui에 추가하였습니다. 
closes #857
> [FE] feat: 고객의 수 추가

- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCouponCommandAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/api/ControllerSliceTest.java
- backend/src/test/java/com/stampcrush/backend/api/manager/cafe/ManagerCafeCouponSettingCommandApiControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/manager/cafe/ManagerCafeCouponSettingFindApiControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/manager/cafe/ManagerCafeFindApiControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/manager/coupon/ManagerCouponCommandApiControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/manager/coupon/ManagerCouponFindApiControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/manager/owner/ManagerCommandApiControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/manager/reward/ManagerRewardFindApiControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/manager/reward/MangerRewardCommandApiControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/manager/sample/ManagerSampleCouponFindApiControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/visitor/cafe/VisitorCafeFindApiControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/visitor/coupon/VisitorCouponCommandApiControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/visitor/coupon/VisitorCouponFindApiControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/visitor/favorites/VisitorFavoritesCommandApiControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/visitor/profile/VisitorProfilesCommandApiControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/visitor/profile/VisitorProfilesFindApiControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/visitor/reward/VisitorRewardsFindControllerTest.java
- backend/src/test/java/com/stampcrush/backend/api/visitor/visithistory/VisitorVisitHistoryFindApiControllerTest.java
- 빈들이랑 어노테이션 다 ControllerSliceTest 에서 상속받도록 했습니다
- ControllerTest 에서 WebMvcConfig Filter 안 걸고 인증 검증하던 메서드들 삭제하였습니다 (스탬프크러쉬 테스트 규칙)
closes
> [BE] refactor: Controller Test 코드를 리팩터링한다

- backend/src/test/java/com/stampcrush/backend/acceptance/AcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCommandAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerJoinAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerRewardCommandAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerRewardFindAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerSampleCouponFindAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/VisitorCafeFindAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/VisitorFavoritesCommandAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/VisitorLinkDataAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/VisitorProfilesCommandAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/step/VisitorJoinStep.java
- Acceptance 테스트에서 사용하는 모든 빈을 최상위 AcceptanceTest 에서 상속받게 다 상위로 올렸습니다
- 기존 존재하는 Fixture 사용 안하고 있는 메서드들 Fixture 사용하도록 수정했습니다
closes
> [BE] refactor: 인수테스트 Fixture 사용하도록, 모든 Bean AccpetanceTest 에서 상속받도록 리팩터링

- frontend/src/components/Template/CustomerTemplate/BottomTabBar/index.tsx
- frontend/src/components/Template/CustomerTemplate/BottomTabBar/style.tsx
- frontend/src/components/Template/style.tsx
- frontend/src/pages/Admin/AdminLogin/style.tsx
- frontend/src/pages/Admin/CustomerList/style.tsx
- frontend/src/pages/Admin/EnterPhoneNumber/components/Dialpad/style.tsx
- frontend/src/pages/Admin/EnterPhoneNumber/style.tsx
트러블 슈팅하는 김에 아이패드 미니 세로까지 대응했습니다.
웹에서 보이는 탭바
iPad mini 세로 모드
closes #867
> [FE] bug: 웹 환경에서 고객모드의 탭바가 보이지 않는 현상을 해결한다.

- frontend/src/pages/Customer/CouponList/components/CouponDetail/style.tsx
- 피드백에 따라 소개 문구가 노출되는 높이를 높였습니다.
- 글자수를 늘리지는 않았습니다. 기종에 따라, 브라우저에 따라 화면에 표기되는 정도가 달라 `%` 단위로 크기를 정했습니다.
closes #882
> [FE] refactor: 소개 문구를 더 많이 보여준다

- frontend/src/components/Alert/index.tsx
- frontend/src/components/Alert/style.tsx
- frontend/src/pages/Admin/EnterPhoneNumber/components/Dialpad/index.tsx
- frontend/src/pages/Admin/EnterPhoneNumber/components/GuideAlert/index.tsx
- frontend/src/pages/Admin/EnterPhoneNumber/components/GuideAlert/style.tsx
- frontend/src/pages/Admin/EnterPhoneNumber/components/PrivacyBox/index.tsx
- frontend/src/pages/Admin/EnterPhoneNumber/components/PrivacyBox/style.tsx
- frontend/src/pages/Admin/EnterPhoneNumber/hooks/useDialPad.ts
- frontend/src/pages/Admin/EnterPhoneNumber/index.tsx
- frontend/src/pages/Admin/EnterPhoneNumber/style.tsx
- 전화번호 입력페이지에서 사용하는 api는 2가지 입니다.
1. 전화번호로 고객 조회(GET)
2. 첫 적립일 경우 임시로 가입시킴(POST)
closes #884
> [FE] feat: 전화번호 입력 페이지의 로딩/에러 핸들링을 개선한다. 

- frontend/src/components/ChoiceTemplate/SampleImageList.tsx
- frontend/src/pages/Admin/ModifyCouponPolicy/components/CurrentCouponImages/index.tsx
- frontend/src/pages/Admin/ModifyCouponPolicy/components/CurrentCouponImages/style.tsx
- #877 
서버 에러 상황을 중점적으로 두었습니다.
그 이유는 현재 미인증 상황일 때는 401로 redirect되고, 클라이언트가 별다른 입력값 예외를 던지지 않는 상황이기 때문에 다음과 같이 구현했습니다.
closes #877
> [FE] refactor: 쿠폰 제작 및 변경 페이지의 로딩/에러 핸들링을 개선한다.

- frontend/src/pages/Admin/RewardPage/components/RewardItemList/index.tsx
- frontend/src/pages/Admin/RewardPage/components/RewardItemList/style.tsx
- frontend/src/pages/Admin/RewardPage/hooks/useMutateReward.ts
- frontend/src/pages/Admin/RewardPage/hooks/useReward.ts
- frontend/src/pages/Admin/RewardPage/index.tsx
- frontend/src/pages/Admin/RewardPage/style.tsx
현재 카페에 적립을 하지 않은 고객의 경우 404로 에러를 발생해, 해당 에러를 이 페이지 내에서 처리 하였습니다.
이 페이지에서 처리한 이유는 해당 에러를 `api/admin/customers/3/rewards?cafe-id=13&used=false`에서 내뱉기 때문에,
EnterPhoneNumber 에서 처리하기 불가능하다고 판단해 처리했습니다..!
사용자에게는 제안사항으로 뒤로가기 버튼을 제공해, 리워드 사용의 enter-phone-number로 이동할 수 있는 버튼을 제공합니다.
그래도 빠른 적립을 위해 몇 가지를 고안해보았습니다.
사장님의 적립 플로우 상 background refetch가 얼마나 일어날까? 하는 생각이 있었습니다.
따라서 background refetch를 삭제했습니다.
기존의 경우 에러가 발생하는 경우 4번정도 시도를 해보고 안되면 에러 페이지를 표시합니다.
그 동안 사용자는 로딩 인디케이터를 보고 있는데 사장님 같은 경우는 빠른 적립 플로우가 필요하므로 안될경우 4번정도 다시 요청을 시도할 것 없이 즉각적으로 에러를 보여주고, 그에 대한 해결책을 빠르게 제공하는게 중요하다고 생각했습니다.
따라서 retry를 없애는 대신 에러에 대해 어떻게 동작할지 제안해주는 화면을 고안해보았습니다.
아래는 404에러 발생시 사용자에게 뒤로가는 동작을 제안하는 화면입니다. 이외의 다른 서버오류는 refetch할 수 있는 동작을 제공합니다.
캡처는 해당 부분만 보이도록 화면 전체 사이즈에 안맞게 캡처한 점 양해 부탁드립니다
|404 에러 화면 | 기타 에러 화면|
|--|--|
|<img …
> [FE] refactor: 리워드 적립 페이지의 로딩/에러 핸들링을 개선한다.

- backend/src/main/java/com/stampcrush/backend/dev/DevAuthController.java
- backend/src/main/java/com/stampcrush/backend/dev/DevAuthService.java
개발환경용 인증 기능 구현했습니다.
- 사장님 가입: `/api/dev/register/admin/{가입시킬 닉네임}`
- 손님 가입:  `/api/dev/visitor/{가입시킬 닉네임}`
- 사장님 로그인: `/api/dev/login/admin/{가입한 닉네임}`
- 손님 로그인: `/api/dev/login/visitor/{가입한 닉네임}`
서브모듈 접근권한이 없어서 테스트는 못 해봤습니다.
그냥 로컬에서 몇번 돌려보고 정삭작동하면 슛 하면 될 듯 합니다.
dev용이므로, 오류가 있다고 해서 치명적이지 않으므로 테스트코드는 따로 작성하지 않았습니다.
closes #907
> [BE] feat: 개발환경용 인증 기능 구현

- frontend/src/components/Alert/style.tsx
- frontend/src/components/BottomTabBar/style.tsx
- frontend/src/components/LoadingSpinner/style.tsx
- frontend/src/components/Modal/style.tsx
- frontend/src/components/SelectBox/style.tsx
- frontend/src/constants/magicNumber.ts
- frontend/src/pages/Admin/EnterPhoneNumber/components/GuideAlert/style.tsx
- frontend/src/pages/Customer/CouponList/components/CafeInfo/style.tsx
- frontend/src/pages/Customer/CouponList/components/CouponDetail/style.tsx
- frontend/src/pages/Customer/CouponList/components/FlippedCoupon/style.tsx
- frontend/src/pages/Customer/CouponList/style.tsx
- frontend/src/pages/Introduction/style.tsx
- frontend/src/style/keyframes.ts
z-index 속성을 많은 곳에서 사용하고 있는데, 숫자의 범위나 기준이 모호한 것 같아 '상수화를 통한 의미부여' 리팩토링을 진행했습니다.
[참고자료](https://velog.io/@nonarnee/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%EC%97%90%EC%84%9C-z-index-%EA%B0%92%EC%9D%84-%EA%B4%80%EB%A6%AC%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95)
```javascript
export const Z_INDEX = {
lowest: -99,
below: -10,
base: 0,
above: 10,
highest: 99,
} as const;
```
변하지 않는 Z_INDEX 객체는 5가지 속성을 가집니다.
header와 같이 base 상태에서 위로 올려야 하는 해야하는 경우는 
```javascript
z-index: ${Z_INDEX.above};
```
alert나 backdrop 과 같이 페이지 최상단에 위치해야 하는 경우
```javascript
export const AlertContainer = styled.div`
...
z-index: ${Z_INDEX.highest + Z_INDEX.above};
`;
export const BackDrop = styled.div`
...
z-index: ${Z_INDEX.highest};
`;
```
다음과 같이 활용해볼 수 있을 것 같습니다.
페이지 내에 여러 z-index 가 존재하는 경우에도
Z_INDEX.above와 Z_INDEX.below 값을 적절히 …
> [FE] refactor: z-index 상수화를 통한 의미 부여

- frontend/src/pages/Customer/CouponList/components/CafeInfo/style.tsx
- frontend/src/pages/Customer/CouponList/style.tsx
- 헤더와 토글의 폰트에서 Layout Shift 발생
- 헤더에 `min-height`, 토글 컨테이너의 `padding`을 `2rem 40px` -> `2rem`으로 변경
+ `BackDrop` 스타일 제거로 인한 오류 해결
closes #912
> [FE] bug: 고객 모드 헤더의 CLS 이슈를 해결한다.

- backend/src/main/java/com/stampcrush/backend/config/WebMvcConfig.java
- backend/src/main/java/com/stampcrush/backend/dev/DevAuthController.java
- backend/src/main/java/com/stampcrush/backend/dev/DevAuthService.java
- backend/src/test/java/com/stampcrush/backend/acceptance/DevAuthAcceptanceTest.java
> [BE] fix: 로그인 진행되지 않는 버그 해결

- backend/src/main/java/com/stampcrush/backend/auth/api/ManagerAuthController.java
- backend/src/main/java/com/stampcrush/backend/auth/api/ManagerReissueTokenController.java
- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerReissueTokenAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerJoinStep.java
- backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerReissueTokenStep.java
리프레시 토큰을 쿠키를 통해 전달하도록 했습니다.
이 과정에서 보안을 위해 HTTP ONLY 속성과, SECURE 속성을 주었고, reissue-token에 대해서만 쿠키가 전달되도록 path를 설정했습니다.
dev서버에서 프론트와 같이 QA해가며 잘 동작하는지 확인할 필요성이 있습니당
코드 중복이 하나 있는데, Controller를 통합하면 줄일 수 있을 것 같으나, 일단은 메서드가 두개이므로 그대로 두었습니다.
closes #931
> [BE] feat: 리프레시 토큰을 쿠키를 통해 전달

- backend/src/main/java/com/stampcrush/backend/api/GlobalExceptionHandler.java
- backend/src/main/java/com/stampcrush/backend/application/manager/cafe/ManagerCafeCommandService.java
- backend/src/main/java/com/stampcrush/backend/application/manager/cafe/ManagerCafeCouponSettingCommandService.java
- backend/src/main/java/com/stampcrush/backend/application/manager/coupon/ManagerCouponCommandService.java
- backend/src/main/java/com/stampcrush/backend/auth/api/VisitorAuthController.java
- backend/src/main/java/com/stampcrush/backend/entity/cafe/CafeCouponDesign.java
- backend/src/main/java/com/stampcrush/backend/entity/cafe/CafePolicy.java
- backend/src/main/java/com/stampcrush/backend/entity/coupon/CouponDesign.java
- backend/src/main/java/com/stampcrush/backend/repository/cafe/CafeCouponDesignRepository.java
- backend/src/main/java/com/stampcrush/backend/repository/cafe/CafePolicyRepository.java
- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCafeCouponSettingCommandUpdateAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCafeCouponSettingFindAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/acceptance/ManagerCouponCommandAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/application/manager/coupon/ManageCouponCommandServiceTest.java
- backend/src/test/java/com/stampcrush/backend/application/manager/coupon/ManagerCouponFindServiceTest.java
- backend/src/test/java/com/stampcrush/backend/entity/cafe/CafePolicyTest.java
- backend/src/test/java/com/stampcrush/backend/fixture/CouponDesignFixture.java
- backend/src/test/java/com/stampcrush/backend/fixture/CouponPolicyFixture.java
- backend/src/test/java/com/stampcrush/backend/repository/cafe/CafeCouponDesignRepositoryTest.java
- backend/src/test/java/com/stampcrush/backend/repository/cafe/CafePolicyRepositoryTest.java
> [BE] feat: deleted로 처리하던 로직을 isActive가 처리하도록 변경

- backend/src/main/java/com/stampcrush/backend/repository/cafe/CafePolicyRepository.java
- backend/src/test/java/com/stampcrush/backend/repository/cafe/CafePolicyRepositoryTest.java
findByCafeAndCreatedAtGreaterThan 을 테스트하는 코드 삭제
closes
> [BE] fix: CafePolicyRepositoryTest 에서 필요없어진 테스트 삭제

- backend/src/main/java/com/stampcrush/backend/application/visitor/profile/VisitorCancelMembershipCommandService.java
- backend/src/main/java/com/stampcrush/backend/repository/coupon/CouponRepository.java
- backend/src/main/java/com/stampcrush/backend/repository/favorites/FavoritesRepository.java
- backend/src/main/java/com/stampcrush/backend/repository/reward/RewardRepository.java
- backend/src/main/java/com/stampcrush/backend/repository/visithistory/VisitHistoryRepository.java
- backend/src/test/java/com/stampcrush/backend/acceptance/VisitorCancelMembershipAcceptanceTest.java
- backend/src/test/java/com/stampcrush/backend/application/visitor/profile/VisitorCancelMembershipCommandServiceTest.java
- backend/src/test/java/com/stampcrush/backend/repository/coupon/CouponRepositoryTest2.java
- backend/src/test/java/com/stampcrush/backend/repository/favorites/FavoritesRepositoryTest.java
- backend/src/test/java/com/stampcrush/backend/repository/reward/RewardRepositoryTest.java
- backend/src/test/java/com/stampcrush/backend/repository/visithistory/VisitHistoryRepositoryTest.java
- 기존에 deleteAll() 을 사용하던 회원 탈퇴 로직을 별도의 JPQL 로 작성한 deleteByCustomer() 로 대체했습니다.
- 회원 탈퇴가 일어나진 않겠지만 그래도 쿼리 개선하고 싶어서 PR 올립니다..!
- `VisitorCancelMembershipAcceptanceTest.이것저것_많이한_회원_탈퇴` 기준 28번의 쿼리 -> 5번의 쿼리로 감소했습니다.
- 기존 엔티티에 모두 @Where 가 붙어 있어서 이를 무시하기 위해 JQPL 에 nativeQuery 옵션 설정했습니다.
- 인수테스트에 탈퇴한 고객의 리워드 같은거 조회해서 빈 배열인지 확인하려고 했는데 이미 탈퇴한 회원으로 조회 요청하면 예외 발생해서 못했습니다. (인증 로직 잘 짰네요 ㅎ)
- 대신 service 테스트를 통해서 deleteByCustomer() 메서드 호출하는지 검증하는 테스트 추가했습니다.
- 각각의 repository 단위테스트도 추가했습니다.
closes
> [BE] feat: 회원 탈퇴 시 발생하는 N+1 문제 해결

- backend/src/main/resources/db/migration/V19__coupon_add_constraint.sql
> [BE] feat: coupon에 cafe_coupon_design_id, cafe_policy_id에 외래키 제약조건 추가
